import type { LegalContentLocale } from "@/lib/legal/content-locales";
import type { LegalDocument } from "./types";

/**
 * SSOT ZH: filix-pay/docs/FilixPay 商户服务协议 V1.md; EN: FilixPay Merchant Service Agreement V1.en.md
 * Generated by scripts/generate-merchant-legal-from-md.mjs — do not hand-edit commercial rules.
 */
const MERCHANT_TERMS_ZH: LegalDocument = {
  "slug": "merchant-terms",
  "status": "draft",
  "title": "FilixPay 商户服务协议",
  "lastUpdated": "2026-09-07",
  "notice": null,
  "sections": [
    {
      "id": "meta",
      "title": "",
      "paragraphs": [
        "Version: V1.0.0",
        "Status: V1",
        "Last Updated: 2026-09-07"
      ]
    },
    {
      "id": "第一条-协议概述",
      "title": "第一条 协议概述",
      "subsections": [
        {
          "id": "1.1",
          "title": "1.1",
          "paragraphs": [
            "本《FilixPay 商户服务协议》（以下简称“本协议”）由 FilixPay 服务提供方（以下简称“FilixPay”）与申请或使用 FilixPay 商户服务的主体（以下简称“商户”）共同订立。",
            "商户通过 FilixPay 网站、商户中心或其他指定方式申请入驻、创建商户业务账号、开通或使用相关服务，即表示商户已阅读、理解并同意受本协议约束。",
            "如商户代表企业、组织或其他主体签署或接受本协议，其确认已获得该主体的合法授权，并有权使该主体受本协议约束。"
          ]
        },
        {
          "id": "1.2",
          "title": "1.2",
          "paragraphs": [
            "本协议适用于商户使用 FilixPay 提供的商户相关服务，包括但不限于：",
            "具体服务是否可用，取决于商户所在地区、业务类型、支付渠道、风险控制、合规要求以及 FilixPay 当时提供的服务范围。"
          ],
          "bullets": [
            "商户中心；",
            "支付基础设施及相关收款能力；",
            "API、SDK、Webhook 等开发者能力；",
            "Sandbox 等测试环境；",
            "FilixPay 电商平台相关服务；",
            "订单及交易相关服务；",
            "与上述服务相关的账户、配置、数据及管理能力。"
          ]
        },
        {
          "id": "1.3",
          "title": "1.3",
          "paragraphs": [
            "FilixPay 是支付及资金流转基础设施服务平台。",
            "除非双方另有明确约定，本协议不构成 FilixPay 向商户提供银行账户、电子钱包、存款账户或其他具有独立法律属性的金融账户。"
          ]
        }
      ]
    },
    {
      "id": "第二条-定义",
      "title": "第二条 定义",
      "paragraphs": [
        "除上下文另有要求外，本协议中的下列术语具有以下含义："
      ],
      "subsections": [
        {
          "id": "2.1-“商户”",
          "title": "2.1 “商户”",
          "paragraphs": [
            "指按照 FilixPay 要求完成注册、入驻、身份或企业信息验证，并获得使用相关商户服务资格的企业、组织或其他合法经营主体。"
          ]
        },
        {
          "id": "2.2-“商户账户”",
          "title": "2.2 “商户账户”",
          "paragraphs": [
            "指 FilixPay 为商户提供，用于访问商户中心、配置服务、查看交易及订单信息以及使用其他商户功能的账户。"
          ]
        },
        {
          "id": "2.3-“业务账号”",
          "title": "2.3 “业务账号”",
          "paragraphs": [
            "指商户在 FilixPay 平台上用于开展特定业务活动的业务主体或业务账户。"
          ]
        },
        {
          "id": "2.4-“SaaS-收款”",
          "title": "2.4 “SaaS 收款”",
          "paragraphs": [
            "指商户使用 FilixPay 提供的支付基础设施及相关 SaaS 能力，为商户自身业务提供收款及相关支付处理服务的业务场景。"
          ]
        },
        {
          "id": "2.5-“电商平台销售订单”",
          "title": "2.5 “电商平台销售订单”",
          "paragraphs": [
            "指商户通过 FilixPay 电商平台产生并完成相应交易流程的销售订单。"
          ]
        },
        {
          "id": "2.6-“服务费”",
          "title": "2.6 “服务费”",
          "paragraphs": [
            "指商户因使用特定 FilixPay 服务而按照适用费率产生的服务费用。"
          ]
        },
        {
          "id": "2.7-“账单”",
          "title": "2.7 “账单”",
          "paragraphs": [
            "指 FilixPay 根据商户在相应账期内产生的应计服务费形成的费用记录或结算凭证。"
          ]
        },
        {
          "id": "2.8-“未结清余额”",
          "title": "2.8 “未结清余额”",
          "paragraphs": [
            "指商户截至特定时间尚未支付的已产生服务费余额。"
          ]
        },
        {
          "id": "2.9-“付款阈值”",
          "title": "2.9 “付款阈值”",
          "paragraphs": [
            "指触发商户服务费付款义务的未结清余额金额。",
            "当前付款阈值为：",
            "人民币 500 元。",
            "人民币 500 元为付款触发阈值，并非免收费额度。"
          ]
        }
      ]
    },
    {
      "id": "第三条-商户入驻",
      "title": "第三条 商户入驻",
      "subsections": [
        {
          "id": "3.1-入驻申请",
          "title": "3.1 入驻申请",
          "paragraphs": [
            "商户申请使用 FilixPay 商户服务时，应按照 FilixPay 要求提供真实、准确、完整且有效的信息。",
            "包括但不限于："
          ],
          "bullets": [
            "企业或组织名称；",
            "注册或经营信息；",
            "联系人信息；",
            "商户经营信息；",
            "商品或服务信息；",
            "结算及收款相关信息；",
            "其他 FilixPay 根据业务、合规或风险控制要求要求提供的信息。"
          ]
        },
        {
          "id": "3.2-信息真实性",
          "title": "3.2 信息真实性",
          "paragraphs": [
            "商户应确保其提交的信息真实、准确、完整，并在相关信息发生变化时及时更新。",
            "商户不得："
          ],
          "bullets": [
            "提供虚假信息；",
            "冒用他人或其他主体身份；",
            "使用未经授权的主体信息；",
            "隐瞒影响服务开通或风险判断的重要信息。"
          ]
        },
        {
          "id": "3.3-审核与验证",
          "title": "3.3 审核与验证",
          "paragraphs": [
            "FilixPay 可根据业务、风险及合规要求对商户进行身份、主体、业务、交易及其他必要的验证。",
            "FilixPay 可要求商户补充资料或重新验证。",
            "在验证完成前，部分服务可能无法开通或使用。"
          ]
        },
        {
          "id": "3.4-商户资格",
          "title": "3.4 商户资格",
          "paragraphs": [
            "完成入驻并不意味着商户自动获得所有 FilixPay 服务或所有支付渠道的使用资格。",
            "具体服务能力以商户中心实际开通状态及 FilixPay 向商户提供的服务为准。"
          ]
        }
      ]
    },
    {
      "id": "第四条-商户账户与组织管理",
      "title": "第四条 商户账户与组织管理",
      "subsections": [
        {
          "id": "4.1",
          "title": "4.1",
          "paragraphs": [
            "商户应妥善管理商户账户及相关登录凭证，并对通过其账户进行的操作承担责任。"
          ]
        },
        {
          "id": "4.2",
          "title": "4.2",
          "paragraphs": [
            "商户应确保其组织成员仅在获得授权的范围内访问和使用 FilixPay。",
            "商户应对其成员的操作进行适当的权限管理。"
          ]
        },
        {
          "id": "4.3",
          "title": "4.3",
          "paragraphs": [
            "如商户发现账户存在未经授权的访问、异常操作或其他安全事件，应及时通知 FilixPay，并采取必要措施降低风险。"
          ]
        },
        {
          "id": "4.4",
          "title": "4.4",
          "paragraphs": [
            "商户不得出售、出租、转让或以其他方式向未经授权的第三方提供商户账户的使用权。"
          ]
        }
      ]
    },
    {
      "id": "第五条-FilixPay-商户服务",
      "title": "第五条 FilixPay 商户服务",
      "subsections": [
        {
          "id": "5.1",
          "title": "5.1",
          "paragraphs": [
            "FilixPay 根据商户实际开通情况提供相应服务。",
            "不同服务可能具有不同的："
          ],
          "bullets": [
            "服务范围；",
            "技术要求；",
            "支付渠道；",
            "交易限制；",
            "风险控制要求；",
            "费用标准；",
            "服务等级。"
          ]
        },
        {
          "id": "5.2",
          "title": "5.2",
          "paragraphs": [
            "FilixPay 可根据产品规划、技术升级、第三方渠道变化、法律法规或风险控制需要，对服务进行更新、调整或停止。",
            "对于可能对商户产生重大影响的服务变化，FilixPay 将按照适用法律及本协议约定进行通知。"
          ]
        },
        {
          "id": "5.3",
          "title": "5.3",
          "paragraphs": [
            "FilixPay 不保证所有支付渠道、地区、资产、币种或服务能力始终可用。",
            "实际可用能力以 FilixPay 当时提供的服务为准。"
          ]
        }
      ]
    },
    {
      "id": "第六条-SaaS-收款服务",
      "title": "第六条 SaaS 收款服务",
      "subsections": [
        {
          "id": "6.1",
          "title": "6.1",
          "paragraphs": [
            "商户可以根据 FilixPay 提供的服务能力使用 SaaS 收款服务，为商户自身业务提供支付及收款基础设施。"
          ]
        },
        {
          "id": "6.2",
          "title": "6.2",
          "paragraphs": [
            "FilixPay SaaS 收款当前平台服务费率为：",
            "0%，即免费。",
            "商户当前无需就符合 SaaS 收款定义的交易向 FilixPay 支付平台服务费。"
          ]
        },
        {
          "id": "6.3",
          "title": "6.3",
          "paragraphs": [
            "上述“免费”仅指 FilixPay 当前平台服务费。",
            "如特定支付渠道、金融机构、第三方服务提供商或其他服务主体依法或根据其自身商业规则收取费用，该等费用不当然属于 FilixPay 平台服务费。",
            "相关费用如适用，应以相应服务规则或实际交易页面展示为准。"
          ]
        },
        {
          "id": "6.4",
          "title": "6.4",
          "paragraphs": [
            "FilixPay 可根据业务发展、服务成本、市场情况或商业政策调整 SaaS 收款服务的收费标准。",
            "未来如 SaaS 收款服务由免费调整为收费，FilixPay 应按照本协议约定的条款变更及通知机制执行。"
          ]
        }
      ]
    },
    {
      "id": "第七条-电商平台服务",
      "title": "第七条 电商平台服务",
      "subsections": [
        {
          "id": "7.1",
          "title": "7.1",
          "paragraphs": [
            "商户可以根据 FilixPay 提供的能力，通过 FilixPay 电商平台创建、发布及销售商品或服务。"
          ]
        },
        {
          "id": "7.2",
          "title": "7.2",
          "paragraphs": [
            "商户通过电商平台产生销售订单的，应遵守 FilixPay 平台规则及适用的商品、交易、内容、消费者保护及合规要求。"
          ]
        },
        {
          "id": "7.3",
          "title": "7.3",
          "paragraphs": [
            "商户应对其在电商平台销售的商品或服务承担经营主体责任，包括但不限于："
          ],
          "bullets": [
            "商品真实性；",
            "商品质量；",
            "商品描述；",
            "价格；",
            "库存；",
            "订单履约；",
            "售后服务；",
            "退款及退货；",
            "消费者权益保护；",
            "依法应承担的税务责任。"
          ]
        },
        {
          "id": "7.4",
          "title": "7.4",
          "paragraphs": [
            "FilixPay 提供电商平台基础设施及相关服务，但除法律另有规定或双方另有约定外，不因此成为商户销售商品或服务的实际经营主体。"
          ]
        }
      ]
    },
    {
      "id": "第八条-电商平台销售订单服务费",
      "title": "第八条 电商平台销售订单服务费",
      "subsections": [
        {
          "id": "8.1",
          "title": "8.1",
          "paragraphs": [
            "商户通过 FilixPay 电商平台产生符合计费条件的销售订单，应按照适用规则支付平台服务费。",
            "当前服务费率为：",
            "订单金额的 5%。"
          ]
        },
        {
          "id": "8.2",
          "title": "8.2",
          "paragraphs": [
            "服务费按照实际发生的符合计费条件的业务订单计算。",
            "当前 V1 规则下：",
            "服务费 = 计费订单金额 × 5%。"
          ]
        },
        {
          "id": "8.3",
          "title": "8.3",
          "paragraphs": [
            "没有符合计费条件的电商平台销售订单，不产生相应的平台服务费。"
          ]
        },
        {
          "id": "8.4",
          "title": "8.4",
          "paragraphs": [
            "订单取消、退款、撤销、异常交易或其他特殊交易可能影响服务费的计算或调整。",
            "具体处理以 FilixPay 当时适用的收费规则及相关业务规则为准。"
          ]
        },
        {
          "id": "8.5",
          "title": "8.5",
          "paragraphs": [
            "FilixPay 可根据商业政策调整电商平台服务费率。",
            "调整应按照本协议及相关收费规则约定的通知和生效机制执行。"
          ]
        }
      ]
    },
    {
      "id": "第九条-服务费账单",
      "title": "第九条 服务费账单",
      "subsections": [
        {
          "id": "9.1",
          "title": "9.1",
          "paragraphs": [
            "FilixPay 按自然月汇总商户上一自然月产生的服务费。"
          ]
        },
        {
          "id": "9.2",
          "title": "9.2",
          "paragraphs": [
            "FilixPay 原则上于：",
            "每月 1 日生成上一自然月服务费账单。",
            "例如：",
            "2026 年 9 月产生的服务费，原则上于 2026 年 10 月 1 日形成对应账单。"
          ]
        },
        {
          "id": "9.3",
          "title": "9.3",
          "paragraphs": [
            "账单可包括："
          ],
          "bullets": [
            "账单周期；",
            "计费订单或交易；",
            "计费金额；",
            "服务费金额；",
            "已支付金额；",
            "未结清余额；",
            "付款状态；",
            "付款期限。"
          ]
        },
        {
          "id": "9.4",
          "title": "9.4",
          "paragraphs": [
            "如因系统维护、节假日、第三方服务异常或其他合理原因导致账单生成时间发生变化，FilixPay 可进行相应调整。"
          ]
        }
      ]
    },
    {
      "id": "第十条-未结清余额与付款阈值",
      "title": "第十条 未结清余额与付款阈值",
      "subsections": [
        {
          "id": "10.1",
          "title": "10.1",
          "paragraphs": [
            "FilixPay 对服务费采用未结清余额累计付款机制。",
            "当前付款阈值为：",
            "人民币 500 元。"
          ]
        },
        {
          "id": "10.2",
          "title": "10.2",
          "paragraphs": [
            "当商户未结清服务费余额低于人民币 500 元时："
          ],
          "bullets": [
            "服务费仍正常产生；",
            "服务费仍计入未结清余额；",
            "商户暂不触发付款义务；",
            "未结清余额继续累计。"
          ]
        },
        {
          "id": "10.3",
          "title": "10.3",
          "paragraphs": [
            "当商户未结清服务费余额达到或超过人民币 500 元时：",
            "商户付款义务被触发。",
            "商户应按照 FilixPay 账单及本协议约定完成付款。"
          ]
        },
        {
          "id": "10.4",
          "title": "10.4",
          "paragraphs": [
            "人民币 500 元为付款触发阈值，不构成任何形式的："
          ],
          "bullets": [
            "免费额度；",
            "服务费减免；",
            "每月免付额度；",
            "费用抵扣额度。"
          ]
        },
        {
          "id": "10.5",
          "title": "10.5",
          "paragraphs": [
            "未结清余额不会因自然月结束而自动清零。",
            "商户未达到付款阈值的服务费，应继续累计至后续账期。"
          ]
        }
      ]
    },
    {
      "id": "第十一条-服务费支付",
      "title": "第十一条 服务费支付",
      "subsections": [
        {
          "id": "11.1",
          "title": "11.1",
          "paragraphs": [
            "当商户未结清服务费余额达到人民币 500 元或以上时，商户应按照账单要求完成支付。"
          ]
        },
        {
          "id": "11.2",
          "title": "11.2",
          "paragraphs": [
            "当前付款期限为：",
            "达到付款阈值后，应于账单生成当月 5 日前完成支付。",
            "例如：",
            "10 月 1 日生成账单，且商户未结清余额达到人民币 500 元，则商户应于 10 月 5 日前完成支付。"
          ]
        },
        {
          "id": "11.3",
          "title": "11.3",
          "paragraphs": [
            "商户可以按照 FilixPay 提供的支付方式完成服务费支付。"
          ]
        },
        {
          "id": "11.4",
          "title": "11.4",
          "paragraphs": [
            "如商户部分支付服务费，剩余未支付金额继续构成未结清余额。"
          ]
        },
        {
          "id": "11.5",
          "title": "11.5",
          "paragraphs": [
            "支付完成后，FilixPay 将按照实际到账金额更新商户服务费未结清余额。"
          ]
        }
      ]
    },
    {
      "id": "第十二条-欠费与服务限制",
      "title": "第十二条 欠费与服务限制",
      "subsections": [
        {
          "id": "12.1",
          "title": "12.1",
          "paragraphs": [
            "商户应按照本协议及账单约定及时支付达到付款阈值的服务费。"
          ]
        },
        {
          "id": "12.2",
          "title": "12.2",
          "paragraphs": [
            "如商户未在规定期限内支付到期服务费，FilixPay 可根据欠费情况、风险程度及本协议约定采取相应措施。",
            "措施可以包括："
          ],
          "bullets": [
            "提醒商户付款；",
            "限制部分服务；",
            "暂停相关服务；",
            "暂停新增交易；",
            "暂停部分商户功能；",
            "要求商户结清欠款后恢复服务；",
            "在法律允许范围内采取其他必要措施。"
          ]
        },
        {
          "id": "12.3",
          "title": "12.3",
          "paragraphs": [
            "服务限制不影响商户在限制发生前已经产生的付款义务。"
          ]
        },
        {
          "id": "12.4",
          "title": "12.4",
          "paragraphs": [
            "商户结清相关欠款后，FilixPay 可根据服务状态、风险及合规情况恢复相应服务。"
          ]
        }
      ]
    },
    {
      "id": "第十三条-商户经营责任",
      "title": "第十三条 商户经营责任",
      "subsections": [
        {
          "id": "13.1",
          "title": "13.1",
          "paragraphs": [
            "商户是其商品、服务及商业活动的责任主体。"
          ]
        },
        {
          "id": "13.2",
          "title": "13.2",
          "paragraphs": [
            "商户应确保其经营活动："
          ],
          "bullets": [
            "合法；",
            "真实；",
            "不侵犯第三方合法权益；",
            "符合适用的消费者保护要求；",
            "符合税务及财务要求；",
            "符合适用的支付及资金流转规则。"
          ]
        },
        {
          "id": "13.3",
          "title": "13.3",
          "paragraphs": [
            "商户不得利用 FilixPay 从事："
          ],
          "bullets": [
            "欺诈；",
            "洗钱；",
            "恐怖融资；",
            "制裁规避；",
            "非法赌博；",
            "非法金融活动；",
            "销售法律禁止的商品或服务；",
            "侵犯知识产权的活动；",
            "其他违法或违反 FilixPay 风险规则的活动。"
          ]
        },
        {
          "id": "13.4",
          "title": "13.4",
          "paragraphs": [
            "商户不得通过拆分交易、虚构交易、伪造订单或其他方式规避 FilixPay 的费用、风控或合规机制。"
          ]
        }
      ]
    },
    {
      "id": "第十四条-合规与风险控制",
      "title": "第十四条 合规与风险控制",
      "subsections": [
        {
          "id": "14.1",
          "title": "14.1",
          "paragraphs": [
            "FilixPay 可根据适用法律法规、支付渠道要求以及自身风险管理政策，对商户、交易、订单及相关活动进行风险控制。"
          ]
        },
        {
          "id": "14.2",
          "title": "14.2",
          "paragraphs": [
            "FilixPay 可以要求商户提供："
          ],
          "bullets": [
            "身份或主体资料；",
            "业务资料；",
            "商品或服务资料；",
            "交易资料；",
            "资金来源或用途相关资料；",
            "其他合理需要的资料。"
          ]
        },
        {
          "id": "14.3",
          "title": "14.3",
          "paragraphs": [
            "如商户未能提供所要求的资料，或 FilixPay 有合理理由认为商户存在重大合规、欺诈或其他风险，FilixPay 可以采取必要措施，包括限制、暂停或终止相关服务。"
          ]
        },
        {
          "id": "14.4",
          "title": "14.4",
          "paragraphs": [
            "商户应配合 FilixPay 及相关服务提供方依法进行的风险、合规及交易审查。"
          ]
        }
      ]
    },
    {
      "id": "第十五条-订单退款与消费者责任",
      "title": "第十五条 订单、退款与消费者责任",
      "subsections": [
        {
          "id": "15.1",
          "title": "15.1",
          "paragraphs": [
            "商户应按照其向消费者作出的商业承诺完成订单履约。"
          ]
        },
        {
          "id": "15.2",
          "title": "15.2",
          "paragraphs": [
            "对于商户原因导致的退款、退货、取消订单或消费者争议，商户应依法承担相应责任。"
          ]
        },
        {
          "id": "15.3",
          "title": "15.3",
          "paragraphs": [
            "FilixPay 可根据实际业务流程向商户提供订单、交易、退款或争议处理能力。"
          ]
        },
        {
          "id": "15.4",
          "title": "15.4",
          "paragraphs": [
            "除法律另有规定外，FilixPay 不替代商户承担其作为商品或服务提供者应承担的经营责任。"
          ]
        }
      ]
    },
    {
      "id": "第十六条-商户数据与隐私",
      "title": "第十六条 商户数据与隐私",
      "subsections": [
        {
          "id": "16.1",
          "title": "16.1",
          "paragraphs": [
            "商户使用 FilixPay 服务过程中产生的数据，按照 FilixPay《隐私政策》以及适用的数据保护规则进行处理。"
          ]
        },
        {
          "id": "16.2",
          "title": "16.2",
          "paragraphs": [
            "商户如通过 FilixPay 处理其客户、消费者或其他第三方的个人信息，应确保其具有合法处理该等数据所需的授权、法律依据及必要告知。"
          ]
        },
        {
          "id": "16.3",
          "title": "16.3",
          "paragraphs": [
            "商户不得利用 FilixPay 服务违法收集、使用、出售、披露或处理个人信息。"
          ]
        },
        {
          "id": "16.4",
          "title": "16.4",
          "paragraphs": [
            "对于商户自行决定收集和处理的数据，商户应依法承担相应的数据保护责任。"
          ]
        }
      ]
    },
    {
      "id": "第十七条-商户内容与知识产权",
      "title": "第十七条 商户内容与知识产权",
      "subsections": [
        {
          "id": "17.1",
          "title": "17.1",
          "paragraphs": [
            "商户在 FilixPay 平台提交或发布的商品信息、图片、文字、品牌、商标及其他内容，其知识产权原则上仍归商户或其合法权利人所有。"
          ]
        },
        {
          "id": "17.2",
          "title": "17.2",
          "paragraphs": [
            "商户授予 FilixPay 为提供、运营、展示、维护及改进相关服务所必要的非独占使用权。"
          ]
        },
        {
          "id": "17.3",
          "title": "17.3",
          "paragraphs": [
            "商户保证其提交的内容不侵犯任何第三方的知识产权、隐私权或其他合法权益。"
          ]
        },
        {
          "id": "17.4",
          "title": "17.4",
          "paragraphs": [
            "FilixPay 的平台软件、技术、商标、界面、文档及其他平台内容，其知识产权归 FilixPay 或相关权利人所有。",
            "未经授权，商户不得复制、出售、出租、反向工程或以其他方式侵犯相关权利。"
          ]
        }
      ]
    },
    {
      "id": "第十八条-第三方服务",
      "title": "第十八条 第三方服务",
      "subsections": [
        {
          "id": "18.1",
          "title": "18.1",
          "paragraphs": [
            "FilixPay 部分服务可能依赖第三方支付机构、银行、支付网络、基础设施提供商、云服务商或其他第三方服务。"
          ]
        },
        {
          "id": "18.2",
          "title": "18.2",
          "paragraphs": [
            "第三方服务可能受其自身协议、服务规则、隐私政策及费用规则约束。"
          ]
        },
        {
          "id": "18.3",
          "title": "18.3",
          "paragraphs": [
            "因第三方服务提供商的系统、网络、政策、服务范围或其他原因导致的服务变化，FilixPay 将在合理范围内进行处理，但不保证第三方服务持续可用。"
          ]
        }
      ]
    },
    {
      "id": "第十九条-服务可用性",
      "title": "第十九条 服务可用性",
      "subsections": [
        {
          "id": "19.1",
          "title": "19.1",
          "paragraphs": [
            "FilixPay 将在合理范围内维护服务的稳定性和安全性。"
          ]
        },
        {
          "id": "19.2",
          "title": "19.2",
          "paragraphs": [
            "因以下原因导致服务中断或受限的，FilixPay 不承担超出法律规定范围的责任："
          ],
          "bullets": [
            "计划维护；",
            "系统升级；",
            "网络故障；",
            "云服务故障；",
            "第三方服务故障；",
            "支付渠道故障；",
            "黑客攻击；",
            "网络安全事件；",
            "不可抗力；",
            "政府或监管机构要求；",
            "法律法规变化；",
            "其他 FilixPay 无法合理控制的事件。"
          ]
        }
      ]
    },
    {
      "id": "第二十条-协议期限",
      "title": "第二十条 协议期限",
      "subsections": [
        {
          "id": "20.1",
          "title": "20.1",
          "paragraphs": [
            "本协议自商户完成接受本协议并获得商户服务资格之日起生效。"
          ]
        },
        {
          "id": "20.2",
          "title": "20.2",
          "paragraphs": [
            "本协议持续有效，直至按照本协议约定终止。"
          ]
        }
      ]
    },
    {
      "id": "第二十一条-商户主动终止",
      "title": "第二十一条 商户主动终止",
      "subsections": [
        {
          "id": "21.1",
          "title": "21.1",
          "paragraphs": [
            "商户可以按照 FilixPay 提供的流程申请停止使用商户服务。"
          ]
        },
        {
          "id": "21.2",
          "title": "21.2",
          "paragraphs": [
            "商户终止服务前，应妥善处理："
          ],
          "bullets": [
            "未完成订单；",
            "消费者退款；",
            "未结清服务费；",
            "其他尚未履行的义务。"
          ]
        },
        {
          "id": "21.3",
          "title": "21.3",
          "paragraphs": [
            "商户停止使用服务不免除终止前已经产生的付款义务及其他应履行的责任。"
          ]
        }
      ]
    },
    {
      "id": "第二十二条-FilixPay-暂停或终止服务",
      "title": "第二十二条 FilixPay 暂停或终止服务",
      "subsections": [
        {
          "id": "22.1",
          "title": "22.1",
          "paragraphs": [
            "出现以下情况之一时，FilixPay 可以暂停或终止全部或部分商户服务："
          ],
          "bullets": [
            "商户违反本协议；",
            "商户违反适用法律法规；",
            "商户存在重大欺诈或安全风险；",
            "商户存在重大合规风险；",
            "商户未按照约定支付应付款项；",
            "商户提供虚假或误导性资料；",
            "商户经营禁止业务；",
            "第三方支付或基础设施服务无法继续提供；",
            "监管机构或其他有权机关要求；",
            "其他根据本协议或适用规则需要采取暂停或终止措施的情况。"
          ]
        },
        {
          "id": "22.2",
          "title": "22.2",
          "paragraphs": [
            "在法律允许且实际可行的情况下，FilixPay 将向商户提供相关通知。",
            "但如果立即采取措施对于防止欺诈、安全风险、违法行为或其他重大风险是必要的，FilixPay 可以先采取措施，再进行通知。"
          ]
        },
        {
          "id": "22.3",
          "title": "22.3",
          "paragraphs": [
            "服务终止不影响终止前已经产生的付款、赔偿、保密、知识产权、数据处理及其他应持续有效的义务。"
          ]
        }
      ]
    },
    {
      "id": "第二十三条-责任与免责声明",
      "title": "第二十三条 责任与免责声明",
      "subsections": [
        {
          "id": "23.1",
          "title": "23.1",
          "paragraphs": [
            "FilixPay 按现有服务能力向商户提供相关基础设施服务。",
            "除法律明确要求外，FilixPay 不保证："
          ],
          "bullets": [
            "服务始终不中断；",
            "所有支付渠道始终可用；",
            "所有交易均可成功完成；",
            "特定业务一定获得盈利；",
            "特定市场或地区始终可以使用相关服务。"
          ]
        },
        {
          "id": "23.2",
          "title": "23.2",
          "paragraphs": [
            "商户应自行判断其经营活动、商品、服务及商业模式是否适合法律法规及其自身业务需求。"
          ]
        },
        {
          "id": "23.3",
          "title": "23.3",
          "paragraphs": [
            "对于因商户自身经营行为、商品或服务、消费者纠纷、税务义务、知识产权争议等产生的责任，原则上由商户自行承担。"
          ]
        },
        {
          "id": "23.4",
          "title": "23.4",
          "paragraphs": [
            "任何一方因本协议产生的责任范围，应受适用法律以及双方有效协议约定的责任限制规则约束。"
          ]
        }
      ]
    },
    {
      "id": "第二十四条-商户赔偿责任",
      "title": "第二十四条 商户赔偿责任",
      "paragraphs": [
        "如因商户违反本协议、违反法律法规、侵犯第三方权利或其经营行为导致 FilixPay 遭受第三方索赔、处罚、损失或合理费用，商户应在适用法律允许范围内承担相应责任。",
        "但如相关损失主要由 FilixPay 自身过错造成，则应根据适用法律及双方责任比例确定各方责任。"
      ]
    },
    {
      "id": "第二十五条-协议变更",
      "title": "第二十五条 协议变更",
      "subsections": [
        {
          "id": "25.1",
          "title": "25.1",
          "paragraphs": [
            "FilixPay 可根据业务发展、服务变化、法律法规或监管要求对本协议进行更新。"
          ]
        },
        {
          "id": "25.2",
          "title": "25.2",
          "paragraphs": [
            "对于重大变更，FilixPay 将通过合理方式向商户进行通知。"
          ]
        },
        {
          "id": "25.3",
          "title": "25.3",
          "paragraphs": [
            "除法律另有要求外，更新后的协议在指定生效日期起适用于后续服务。"
          ]
        },
        {
          "id": "25.4",
          "title": "25.4",
          "paragraphs": [
            "如果商户不同意重大变更，可以停止使用相关服务并按照规定终止商户服务。",
            "在变更生效后继续使用相关服务的，视为接受更新后的协议。"
          ]
        }
      ]
    },
    {
      "id": "第二十六条-商户服务费规则的变更",
      "title": "第二十六条 商户服务费规则的变更",
      "subsections": [
        {
          "id": "26.1",
          "title": "26.1",
          "paragraphs": [
            "当前主要服务费标准为：",
            "服务类型：服务费",
            "FilixPay SaaS 收款：0%（免费）",
            "FilixPay 电商平台销售订单：5%"
          ]
        },
        {
          "id": "26.2",
          "title": "26.2",
          "paragraphs": [
            "FilixPay 可以根据业务发展调整服务费率、收费项目、计费规则或付款规则。"
          ]
        },
        {
          "id": "26.3",
          "title": "26.3",
          "paragraphs": [
            "涉及商户重大付款义务变化的，FilixPay 应按照本协议约定向商户进行通知，并在适用法律允许的范围内确定生效时间。"
          ]
        },
        {
          "id": "26.4",
          "title": "26.4",
          "paragraphs": [
            "商户已经产生且在变更生效前应支付的服务费，不因后续收费规则变更而当然免除。"
          ]
        }
      ]
    },
    {
      "id": "第二十七条-通知",
      "title": "第二十七条 通知",
      "subsections": [
        {
          "id": "27.1",
          "title": "27.1",
          "paragraphs": [
            "FilixPay 可以通过以下方式向商户发送通知："
          ],
          "bullets": [
            "商户中心；",
            "注册邮箱；",
            "账户内通知；",
            "网站公告；",
            "其他合理方式。"
          ]
        },
        {
          "id": "27.2",
          "title": "27.2",
          "paragraphs": [
            "商户应确保其联系方式真实、有效，并及时更新。",
            "因商户未及时更新联系方式导致无法接收通知的，FilixPay 不因此承担额外责任。"
          ]
        }
      ]
    },
    {
      "id": "第二十八条-保密",
      "title": "第二十八条 保密",
      "paragraphs": [
        "双方对于在使用本协议项下服务过程中获得的对方非公开信息，应采取合理措施予以保密。",
        "法律法规、监管要求或有权机关要求披露的除外。",
        "本条不限制 FilixPay 为提供服务、进行风险控制、合规审查、账务处理或使用必要的第三方服务而依法处理相关信息。"
      ]
    },
    {
      "id": "第二十九条-协议关系",
      "title": "第二十九条 协议关系",
      "subsections": [
        {
          "id": "29.1",
          "title": "29.1",
          "paragraphs": [
            "本协议与以下文件共同构成商户使用 FilixPay 服务的规则体系："
          ],
          "bullets": [
            "《FilixPay 服务条款》；",
            "《FilixPay 隐私政策》；",
            "《FilixPay 商户服务与收费规则》；",
            "具体产品或服务规则；",
            "双方另行签署的商业协议、订单或其他书面文件。"
          ]
        },
        {
          "id": "29.2",
          "title": "29.2",
          "paragraphs": [
            "对于同一事项存在不同约定的，应按照以下原则确定适用顺序：",
            "但涉及数据保护、隐私、安全或监管要求的事项，应同时遵守适用法律及相关专门规则。"
          ],
          "orderedBullets": [
            "双方针对特定服务签署的专项书面协议；",
            "本协议；",
            "针对商户服务的专项收费及产品规则；",
            "FilixPay 通用服务条款；",
            "其他一般性平台规则。"
          ]
        }
      ]
    },
    {
      "id": "第三十条-不构成代理或合伙关系",
      "title": "第三十条 不构成代理或合伙关系",
      "paragraphs": [
        "除双方另有明确书面约定外，本协议不构成：",
        "任何一方不得未经授权代表另一方作出承诺。"
      ],
      "bullets": [
        "合伙；",
        "代理；",
        "雇佣；",
        "特许经营；",
        "联营；",
        "商业代表关系。"
      ]
    },
    {
      "id": "第三十一条-不可抗力",
      "title": "第三十一条 不可抗力",
      "paragraphs": [
        "因超出合理控制范围的事件导致一方无法或延迟履行本协议义务的，该方在法律允许范围内不承担因该等延迟产生的责任。",
        "不可抗力事件包括但不限于：",
        "受影响的一方应在合理范围内采取措施降低影响。"
      ],
      "bullets": [
        "自然灾害；",
        "战争；",
        "恐怖活动；",
        "大规模网络攻击；",
        "重大基础设施故障；",
        "政府行为；",
        "重大公共事件；",
        "法律法规或监管政策变化；",
        "其他无法合理预见、避免或克服的事件。"
      ]
    },
    {
      "id": "第三十二条-条款独立性",
      "title": "第三十二条 条款独立性",
      "paragraphs": [
        "如果本协议任何条款被认定为无效、违法或不可执行，该条款应在必要范围内进行调整或视为不适用，但不影响其他条款的有效性。"
      ]
    },
    {
      "id": "第三十三条-权利义务转让",
      "title": "第三十三条 权利义务转让",
      "paragraphs": [
        "未经对方事先书面同意，任何一方不得将本协议项下主要权利义务整体转让给第三方，但法律允许或因企业重组、合并、收购等合理商业安排而发生的转让除外。"
      ]
    },
    {
      "id": "第三十四条-完整协议",
      "title": "第三十四条 完整协议",
      "paragraphs": [
        "本协议以及其明确纳入的相关规则构成双方就商户服务事项达成的完整协议。",
        "如双方另行签署书面协议，对特定事项作出不同约定，则以该专项协议约定为准。"
      ]
    },
    {
      "id": "第三十五条-适用法律与争议解决",
      "title": "第三十五条 适用法律与争议解决",
      "paragraphs": [
        "本协议的适用法律、管辖及争议解决方式，应以 FilixPay 实际签约主体及其商业运营地区确定。",
        "正式发布本协议前，FilixPay 应补充并确认：",
        "在上述信息正式确定前，本条不应被解释为对特定司法管辖区的最终选择。"
      ],
      "bullets": [
        "签约主体的完整法定名称；",
        "注册地或主要营业地；",
        "适用法律；",
        "管辖法院或仲裁机构；",
        "争议解决地点；",
        "正式法律通知地址。"
      ]
    },
    {
      "id": "第三十六条-联系我们",
      "title": "第三十六条 联系我们",
      "paragraphs": [
        "如商户对本协议、商户服务、服务费账单或其他相关事项存在疑问，可以通过 FilixPay 网站及商户中心公布的官方联系方式与 FilixPay 联系。",
        "正式发布版本应补充 FilixPay 实际使用的："
      ],
      "bullets": [
        "商务联系方式；",
        "法律通知邮箱；",
        "商户服务支持渠道；",
        "其他必要的法定联系信息。"
      ]
    },
    {
      "id": "第三十七条-生效",
      "title": "第三十七条 生效",
      "paragraphs": [
        "本协议自商户按照 FilixPay 指定方式完成接受之日起生效。",
        "商户完成入驻、开通或继续使用相关商户服务，即表示商户确认已阅读、理解并接受本协议及适用于其服务的相关规则。"
      ]
    },
    {
      "id": "附件一商户服务费摘要",
      "title": "附件一：商户服务费摘要",
      "paragraphs": [
        "项目：V1 规则",
        "FilixPay SaaS 收款：免费（0%）",
        "电商平台销售订单：5%",
        "服务费产生：产生符合计费条件的订单或交易时产生",
        "账单周期：自然月",
        "账单生成时间：每月 1 日生成上月账单",
        "付款阈值：未结清余额累计达到 ¥500",
        "付款期限：达到阈值后，于账单生成当月 5 日前支付",
        "未达到 ¥500：暂不触发付款义务，余额继续累计",
        "¥500 的性质：付款触发阈值，不是免收费额度",
        "未结清余额：不因自然月结束自动清零"
      ]
    },
    {
      "id": "附件二核心商业规则",
      "title": "附件二：核心商业规则",
      "subsections": [
        {
          "id": "1.-SaaS-收款",
          "title": "1. SaaS 收款",
          "paragraphs": [
            "FilixPay SaaS 收款当前免费。"
          ]
        },
        {
          "id": "2.-电商平台销售",
          "title": "2. 电商平台销售",
          "paragraphs": [
            "通过 FilixPay 电商平台产生的销售订单，当前按订单金额的 5% 收取平台服务费。"
          ]
        },
        {
          "id": "3.-服务费付款",
          "title": "3. 服务费付款",
          "paragraphs": [
            "服务费按实际产生的符合计费条件的业务事件计算，每月 1 日生成上月账单。未结清余额低于人民币 500 元时暂不触发付款义务；当未结清余额达到或超过人民币 500 元时，触发付款义务，商户应于当月 5 日前完成支付。"
          ]
        },
        {
          "id": "4.-阈值性质",
          "title": "4. 阈值性质",
          "paragraphs": [
            "人民币 500 元为付款触发阈值，不是免费额度、免收费额度或每月费用减免额度。",
            "最后更新：2026 年 9 月 7 日"
          ]
        }
      ]
    }
  ]
} as LegalDocument;

const MERCHANT_TERMS_EN: LegalDocument = {
  "slug": "merchant-terms",
  "status": "draft",
  "title": "FilixPay Merchant Service Agreement",
  "lastUpdated": "2026-09-07",
  "notice": null,
  "sections": [
    {
      "id": "meta",
      "title": "",
      "paragraphs": [
        "Version: V1.0.0",
        "Status: V1",
        "Last Updated: 2026-09-07"
      ]
    },
    {
      "id": "Article-1-Overview",
      "title": "Article 1 Overview",
      "subsections": [
        {
          "id": "1.1",
          "title": "1.1",
          "paragraphs": [
            "This FilixPay Merchant Service Agreement (hereinafter the “Agreement”) is entered into by and between the FilixPay service provider (hereinafter “FilixPay”) and the entity that applies for or uses FilixPay merchant services (hereinafter the “Merchant”).",
            "By applying for onboarding, creating a merchant business account, activating or using relevant services through the FilixPay website, Merchant Center, or other designated means, the Merchant represents that it has read, understood, and agreed to be bound by this Agreement.",
            "If the Merchant signs or accepts this Agreement on behalf of an enterprise, organization, or other entity, it confirms that it has obtained lawful authorization from such entity and has the authority to bind such entity to this Agreement."
          ]
        },
        {
          "id": "1.2",
          "title": "1.2",
          "paragraphs": [
            "This Agreement applies to the Merchant’s use of merchant-related services provided by FilixPay, including without limitation:",
            "Whether specific services are available depends on the Merchant’s region, business type, payment channels, risk controls, compliance requirements, and the scope of services then offered by FilixPay."
          ],
          "bullets": [
            "Merchant Center;",
            "payment infrastructure and related collection capabilities;",
            "developer capabilities such as APIs, SDKs, and Webhooks;",
            "testing environments such as Sandbox;",
            "FilixPay e-commerce platform-related services;",
            "order- and transaction-related services;",
            "account, configuration, data, and management capabilities related to the foregoing services."
          ]
        },
        {
          "id": "1.3",
          "title": "1.3",
          "paragraphs": [
            "FilixPay is a payment and funds-flow infrastructure service platform.",
            "Unless otherwise expressly agreed by the parties, this Agreement does not constitute the provision by FilixPay to the Merchant of a bank account, electronic wallet, deposit account, or any other financial account having independent legal attributes."
          ]
        }
      ]
    },
    {
      "id": "Article-2-Definitions",
      "title": "Article 2 Definitions",
      "paragraphs": [
        "Unless the context otherwise requires, the following terms in this Agreement have the meanings set forth below:"
      ],
      "subsections": [
        {
          "id": "2.1-“Merchant”",
          "title": "2.1 “Merchant”",
          "paragraphs": [
            "Means an enterprise, organization, or other lawfully operating entity that has completed registration, onboarding, and identity or enterprise information verification in accordance with FilixPay’s requirements and has obtained eligibility to use the relevant merchant services."
          ]
        },
        {
          "id": "2.2-“Merchant-Account”",
          "title": "2.2 “Merchant Account”",
          "paragraphs": [
            "Means the account provided by FilixPay to the Merchant for accessing the Merchant Center, configuring services, viewing transaction and order information, and using other merchant functions."
          ]
        },
        {
          "id": "2.3-“Business-Account”",
          "title": "2.3 “Business Account”",
          "paragraphs": [
            "Means the business entity or business account used by the Merchant on the FilixPay platform to conduct specific business activities."
          ]
        },
        {
          "id": "2.4-“SaaS-Collection”",
          "title": "2.4 “SaaS Collection”",
          "paragraphs": [
            "Means the business scenario in which the Merchant uses the payment infrastructure and related SaaS capabilities provided by FilixPay to provide collection and related payment processing services for the Merchant’s own business."
          ]
        },
        {
          "id": "2.5-“E-commerce-Platform-Sales-Order”",
          "title": "2.5 “E-commerce Platform Sales Order”",
          "paragraphs": [
            "Means a sales order generated and for which the corresponding transaction process is completed through the FilixPay e-commerce platform."
          ]
        },
        {
          "id": "2.6-“Service-Fees”",
          "title": "2.6 “Service Fees”",
          "paragraphs": [
            "Means the service charges incurred by the Merchant at the applicable rates for using specific FilixPay services."
          ]
        },
        {
          "id": "2.7-“Invoice”-/-“Bill”",
          "title": "2.7 “Invoice” / “Bill”",
          "paragraphs": [
            "Means the fee record or settlement voucher formed by FilixPay based on the Service Fees accrued by the Merchant during the relevant billing period."
          ]
        },
        {
          "id": "2.8-“Outstanding-Balance”",
          "title": "2.8 “Outstanding Balance”",
          "paragraphs": [
            "Means the balance of accrued Service Fees that the Merchant has not yet paid as of a given time."
          ]
        },
        {
          "id": "2.9-“Payment-Threshold”",
          "title": "2.9 “Payment Threshold”",
          "paragraphs": [
            "Means the Outstanding Balance amount that triggers the Merchant’s obligation to pay Service Fees.",
            "The current Payment Threshold is:",
            "RMB 500.",
            "RMB 500 is a payment-trigger threshold, not a free allowance."
          ]
        }
      ]
    },
    {
      "id": "Article-3-Merchant-Onboarding",
      "title": "Article 3 Merchant Onboarding",
      "subsections": [
        {
          "id": "3.1-Onboarding-Application",
          "title": "3.1 Onboarding Application",
          "paragraphs": [
            "When applying to use FilixPay merchant services, the Merchant shall provide true, accurate, complete, and valid information in accordance with FilixPay’s requirements.",
            "Including without limitation:"
          ],
          "bullets": [
            "enterprise or organization name;",
            "registration or operating information;",
            "contact person information;",
            "Merchant business information;",
            "goods or services information;",
            "settlement and collection-related information;",
            "other information that FilixPay requires based on business, compliance, or risk-control needs."
          ]
        },
        {
          "id": "3.2-Truthfulness-of-Information",
          "title": "3.2 Truthfulness of Information",
          "paragraphs": [
            "The Merchant shall ensure that the information it submits is true, accurate, and complete, and shall promptly update such information when it changes.",
            "The Merchant shall not:"
          ],
          "bullets": [
            "provide false information;",
            "impersonate another person or entity;",
            "use unauthorized entity information;",
            "conceal material information that affects service activation or risk assessment."
          ]
        },
        {
          "id": "3.3-Review-and-Verification",
          "title": "3.3 Review and Verification",
          "paragraphs": [
            "FilixPay may, based on business, risk, and compliance requirements, conduct identity, entity, business, transaction, and other necessary verification of the Merchant.",
            "FilixPay may require the Merchant to supplement materials or undergo re-verification.",
            "Before verification is completed, certain services may be unavailable for activation or use."
          ]
        },
        {
          "id": "3.4-Merchant-Eligibility",
          "title": "3.4 Merchant Eligibility",
          "paragraphs": [
            "Completion of onboarding does not mean that the Merchant automatically obtains eligibility to use all FilixPay services or all payment channels.",
            "Specific service capabilities are subject to the actual activation status in the Merchant Center and the services provided by FilixPay to the Merchant."
          ]
        }
      ]
    },
    {
      "id": "Article-4-Merchant-Account-and-Organization-Management",
      "title": "Article 4 Merchant Account and Organization Management",
      "subsections": [
        {
          "id": "4.1",
          "title": "4.1",
          "paragraphs": [
            "The Merchant shall properly manage its Merchant Account and related login credentials, and shall be responsible for operations conducted through its account."
          ]
        },
        {
          "id": "4.2",
          "title": "4.2",
          "paragraphs": [
            "The Merchant shall ensure that its organization members access and use FilixPay only within the scope of their authorization.",
            "The Merchant shall implement appropriate permission management over its members’ operations."
          ]
        },
        {
          "id": "4.3",
          "title": "4.3",
          "paragraphs": [
            "If the Merchant discovers unauthorized access, abnormal operations, or other security incidents involving its account, it shall promptly notify FilixPay and take necessary measures to mitigate risk."
          ]
        },
        {
          "id": "4.4",
          "title": "4.4",
          "paragraphs": [
            "The Merchant shall not sell, lease, transfer, or otherwise provide the right to use the Merchant Account to any unauthorized third party."
          ]
        }
      ]
    },
    {
      "id": "Article-5-FilixPay-Merchant-Services",
      "title": "Article 5 FilixPay Merchant Services",
      "subsections": [
        {
          "id": "5.1",
          "title": "5.1",
          "paragraphs": [
            "FilixPay provides corresponding services based on the Merchant’s actual activation status.",
            "Different services may have different:"
          ],
          "bullets": [
            "service scopes;",
            "technical requirements;",
            "payment channels;",
            "transaction restrictions;",
            "risk-control requirements;",
            "fee standards;",
            "service levels."
          ]
        },
        {
          "id": "5.2",
          "title": "5.2",
          "paragraphs": [
            "FilixPay may update, adjust, or discontinue services based on product planning, technical upgrades, changes in third-party channels, laws and regulations, or risk-control needs.",
            "For service changes that may have a material impact on the Merchant, FilixPay will provide notice in accordance with applicable law and this Agreement."
          ]
        },
        {
          "id": "5.3",
          "title": "5.3",
          "paragraphs": [
            "FilixPay does not guarantee that all payment channels, regions, assets, currencies, or service capabilities will always be available.",
            "Actual available capabilities are subject to the services then offered by FilixPay."
          ]
        }
      ]
    },
    {
      "id": "Article-6-SaaS-Collection-Services",
      "title": "Article 6 SaaS Collection Services",
      "subsections": [
        {
          "id": "6.1",
          "title": "6.1",
          "paragraphs": [
            "The Merchant may, based on the capabilities provided by FilixPay, use SaaS Collection services to obtain payment and collection infrastructure for the Merchant’s own business."
          ]
        },
        {
          "id": "6.2",
          "title": "6.2",
          "paragraphs": [
            "The current FilixPay SaaS Collection platform service fee rate is:",
            "0%, i.e., free of charge.",
            "The Merchant currently is not required to pay FilixPay any platform service fee for transactions that fall within the definition of SaaS Collection."
          ]
        },
        {
          "id": "6.3",
          "title": "6.3",
          "paragraphs": [
            "The foregoing “free of charge” refers only to FilixPay’s current platform service fee.",
            "If a specific payment channel, financial institution, third-party service provider, or other service entity charges fees pursuant to law or its own commercial rules, such fees do not automatically constitute FilixPay platform service fees.",
            "Where applicable, such fees shall be subject to the relevant service rules or the information displayed on the actual transaction page."
          ]
        },
        {
          "id": "6.4",
          "title": "6.4",
          "paragraphs": [
            "FilixPay may adjust the fee standards for SaaS Collection services based on business development, service costs, market conditions, or commercial policy.",
            "If SaaS Collection services are in the future adjusted from free to fee-based, FilixPay shall implement such change in accordance with the amendment and notice mechanisms set forth in this Agreement."
          ]
        }
      ]
    },
    {
      "id": "Article-7-E-commerce-Platform-Services",
      "title": "Article 7 E-commerce Platform Services",
      "subsections": [
        {
          "id": "7.1",
          "title": "7.1",
          "paragraphs": [
            "The Merchant may, based on the capabilities provided by FilixPay, create, publish, and sell goods or services through the FilixPay e-commerce platform."
          ]
        },
        {
          "id": "7.2",
          "title": "7.2",
          "paragraphs": [
            "Where the Merchant generates sales orders through the e-commerce platform, it shall comply with FilixPay platform rules and applicable requirements regarding goods, transactions, content, consumer protection, and compliance."
          ]
        },
        {
          "id": "7.3",
          "title": "7.3",
          "paragraphs": [
            "The Merchant shall bear operator responsibility for the goods or services it sells on the e-commerce platform, including without limitation:"
          ],
          "bullets": [
            "authenticity of goods;",
            "quality of goods;",
            "product descriptions;",
            "pricing;",
            "inventory;",
            "order fulfillment;",
            "after-sales service;",
            "refunds and returns;",
            "consumer rights protection;",
            "tax obligations that it is legally required to bear."
          ]
        },
        {
          "id": "7.4",
          "title": "7.4",
          "paragraphs": [
            "FilixPay provides e-commerce platform infrastructure and related services, but except as otherwise provided by law or agreed by the parties, does not thereby become the actual operator of the goods or services sold by the Merchant."
          ]
        }
      ]
    },
    {
      "id": "Article-8-E-commerce-Platform-Sales-Order-Service-Fees",
      "title": "Article 8 E-commerce Platform Sales Order Service Fees",
      "subsections": [
        {
          "id": "8.1",
          "title": "8.1",
          "paragraphs": [
            "Where the Merchant generates sales orders through the FilixPay e-commerce platform that meet billing conditions, it shall pay platform service fees in accordance with the applicable rules.",
            "The current service fee rate is:",
            "5% of the order amount."
          ]
        },
        {
          "id": "8.2",
          "title": "8.2",
          "paragraphs": [
            "Service Fees are calculated based on business orders that actually occur and meet billing conditions.",
            "Under the current V1 rules:",
            "Service Fee = billable order amount × 5%."
          ]
        },
        {
          "id": "8.3",
          "title": "8.3",
          "paragraphs": [
            "If there are no e-commerce platform sales orders that meet billing conditions, no corresponding platform service fees will accrue."
          ]
        },
        {
          "id": "8.4",
          "title": "8.4",
          "paragraphs": [
            "Order cancellations, refunds, reversals, abnormal transactions, or other special transactions may affect the calculation or adjustment of Service Fees.",
            "Specific handling shall be subject to FilixPay’s then-applicable fee rules and related business rules."
          ]
        },
        {
          "id": "8.5",
          "title": "8.5",
          "paragraphs": [
            "FilixPay may adjust e-commerce platform service fee rates based on commercial policy.",
            "Any adjustment shall be implemented in accordance with the notice and effective-date mechanisms set forth in this Agreement and the relevant fee rules."
          ]
        }
      ]
    },
    {
      "id": "Article-9-Service-Fee-Invoices-/-Bills",
      "title": "Article 9 Service Fee Invoices / Bills",
      "subsections": [
        {
          "id": "9.1",
          "title": "9.1",
          "paragraphs": [
            "FilixPay aggregates, on a calendar-month basis, the Service Fees incurred by the Merchant in the preceding calendar month."
          ]
        },
        {
          "id": "9.2",
          "title": "9.2",
          "paragraphs": [
            "In principle, FilixPay will:",
            "generate on the 1st day of each month the Service Fee invoice/bill for the preceding calendar month.",
            "For example:",
            "Service Fees incurred in September 2026 will, in principle, form the corresponding invoice/bill on October 1, 2026."
          ]
        },
        {
          "id": "9.3",
          "title": "9.3",
          "paragraphs": [
            "An invoice/bill may include:"
          ],
          "bullets": [
            "billing period;",
            "billable orders or transactions;",
            "billable amounts;",
            "Service Fee amounts;",
            "amounts already paid;",
            "Outstanding Balance;",
            "payment status;",
            "payment deadline."
          ]
        },
        {
          "id": "9.4",
          "title": "9.4",
          "paragraphs": [
            "If the invoice/bill generation time changes due to system maintenance, holidays, third-party service anomalies, or other reasonable causes, FilixPay may make corresponding adjustments."
          ]
        }
      ]
    },
    {
      "id": "Article-10-Outstanding-Balance-and-Payment-Threshold",
      "title": "Article 10 Outstanding Balance and Payment Threshold",
      "subsections": [
        {
          "id": "10.1",
          "title": "10.1",
          "paragraphs": [
            "FilixPay adopts an Outstanding Balance accrual payment mechanism for Service Fees.",
            "The current Payment Threshold is:",
            "RMB 500."
          ]
        },
        {
          "id": "10.2",
          "title": "10.2",
          "paragraphs": [
            "When the Merchant’s Outstanding Service Fee Balance is below RMB 500:"
          ],
          "bullets": [
            "Service Fees continue to accrue normally;",
            "Service Fees continue to be included in the Outstanding Balance;",
            "the Merchant’s payment obligation is not yet triggered;",
            "the Outstanding Balance continues to accumulate."
          ]
        },
        {
          "id": "10.3",
          "title": "10.3",
          "paragraphs": [
            "When the Merchant’s Outstanding Service Fee Balance reaches or exceeds RMB 500:",
            "the Merchant’s payment obligation is triggered.",
            "The Merchant shall complete payment in accordance with the FilixPay invoice/bill and this Agreement."
          ]
        },
        {
          "id": "10.4",
          "title": "10.4",
          "paragraphs": [
            "RMB 500 is a payment-trigger threshold and does not constitute any form of:"
          ],
          "bullets": [
            "free allowance;",
            "Service Fee waiver;",
            "monthly payment-free allowance;",
            "fee deduction allowance."
          ]
        },
        {
          "id": "10.5",
          "title": "10.5",
          "paragraphs": [
            "The Outstanding Balance does not automatically clear upon the end of a calendar month.",
            "Service Fees for which the Merchant has not reached the Payment Threshold shall continue to accumulate into subsequent billing periods."
          ]
        }
      ]
    },
    {
      "id": "Article-11-Payment-of-Service-Fees",
      "title": "Article 11 Payment of Service Fees",
      "subsections": [
        {
          "id": "11.1",
          "title": "11.1",
          "paragraphs": [
            "When the Merchant’s Outstanding Service Fee Balance reaches RMB 500 or more, the Merchant shall complete payment in accordance with the invoice/bill requirements."
          ]
        },
        {
          "id": "11.2",
          "title": "11.2",
          "paragraphs": [
            "The current payment deadline is:",
            "After the Payment Threshold is reached, payment shall be completed by the 5th day of the month in which the invoice/bill is generated.",
            "For example:",
            "If an invoice/bill is generated on October 1 and the Merchant’s Outstanding Balance has reached RMB 500, the Merchant shall complete payment by October 5."
          ]
        },
        {
          "id": "11.3",
          "title": "11.3",
          "paragraphs": [
            "The Merchant may complete payment of Service Fees using the payment methods provided by FilixPay."
          ]
        },
        {
          "id": "11.4",
          "title": "11.4",
          "paragraphs": [
            "If the Merchant makes a partial payment of Service Fees, the remaining unpaid amount continues to constitute the Outstanding Balance."
          ]
        },
        {
          "id": "11.5",
          "title": "11.5",
          "paragraphs": [
            "After payment is completed, FilixPay will update the Merchant’s Outstanding Service Fee Balance based on the amount actually received."
          ]
        }
      ]
    },
    {
      "id": "Article-12-Delinquency-and-Service-Restrictions",
      "title": "Article 12 Delinquency and Service Restrictions",
      "subsections": [
        {
          "id": "12.1",
          "title": "12.1",
          "paragraphs": [
            "The Merchant shall timely pay Service Fees that have reached the Payment Threshold in accordance with this Agreement and the invoice/bill."
          ]
        },
        {
          "id": "12.2",
          "title": "12.2",
          "paragraphs": [
            "If the Merchant fails to pay due Service Fees within the prescribed period, FilixPay may take corresponding measures based on the delinquency, the degree of risk, and this Agreement.",
            "Such measures may include:"
          ],
          "bullets": [
            "reminding the Merchant to pay;",
            "restricting certain services;",
            "suspending relevant services;",
            "suspending new transactions;",
            "suspending certain merchant functions;",
            "requiring the Merchant to settle arrears before restoring services;",
            "taking other necessary measures to the extent permitted by law."
          ]
        },
        {
          "id": "12.3",
          "title": "12.3",
          "paragraphs": [
            "Service restrictions do not affect payment obligations that have already arisen before the restrictions take effect."
          ]
        },
        {
          "id": "12.4",
          "title": "12.4",
          "paragraphs": [
            "After the Merchant settles the relevant arrears, FilixPay may restore the corresponding services based on service status, risk, and compliance circumstances."
          ]
        }
      ]
    },
    {
      "id": "Article-13-Merchant-Operating-Responsibilities",
      "title": "Article 13 Merchant Operating Responsibilities",
      "subsections": [
        {
          "id": "13.1",
          "title": "13.1",
          "paragraphs": [
            "The Merchant is the party responsible for its goods, services, and commercial activities."
          ]
        },
        {
          "id": "13.2",
          "title": "13.2",
          "paragraphs": [
            "The Merchant shall ensure that its business activities are:"
          ],
          "bullets": [
            "lawful;",
            "genuine;",
            "not infringing upon the lawful rights and interests of third parties;",
            "compliant with applicable consumer protection requirements;",
            "compliant with tax and financial requirements;",
            "compliant with applicable payment and funds-flow rules."
          ]
        },
        {
          "id": "13.3",
          "title": "13.3",
          "paragraphs": [
            "The Merchant shall not use FilixPay to engage in:"
          ],
          "bullets": [
            "fraud;",
            "money laundering;",
            "terrorist financing;",
            "sanctions evasion;",
            "illegal gambling;",
            "illegal financial activities;",
            "sale of goods or services prohibited by law;",
            "activities that infringe intellectual property rights;",
            "other illegal activities or activities that violate FilixPay risk rules."
          ]
        },
        {
          "id": "13.4",
          "title": "13.4",
          "paragraphs": [
            "The Merchant shall not circumvent FilixPay’s fee, risk-control, or compliance mechanisms by splitting transactions, fabricating transactions, forging orders, or other means."
          ]
        }
      ]
    },
    {
      "id": "Article-14-Compliance-and-Risk-Control",
      "title": "Article 14 Compliance and Risk Control",
      "subsections": [
        {
          "id": "14.1",
          "title": "14.1",
          "paragraphs": [
            "FilixPay may, pursuant to applicable laws and regulations, payment channel requirements, and its own risk-management policies, conduct risk control over the Merchant, transactions, orders, and related activities."
          ]
        },
        {
          "id": "14.2",
          "title": "14.2",
          "paragraphs": [
            "FilixPay may require the Merchant to provide:"
          ],
          "bullets": [
            "identity or entity materials;",
            "business materials;",
            "goods or services materials;",
            "transaction materials;",
            "materials relating to the source or use of funds;",
            "other reasonably necessary materials."
          ]
        },
        {
          "id": "14.3",
          "title": "14.3",
          "paragraphs": [
            "If the Merchant fails to provide the required materials, or if FilixPay has reasonable grounds to believe that the Merchant presents material compliance, fraud, or other risks, FilixPay may take necessary measures, including restricting, suspending, or terminating relevant services."
          ]
        },
        {
          "id": "14.4",
          "title": "14.4",
          "paragraphs": [
            "The Merchant shall cooperate with FilixPay and related service providers in lawfully conducting risk, compliance, and transaction reviews."
          ]
        }
      ]
    },
    {
      "id": "Article-15-Orders,-Refunds,-and-Consumer-Responsibilities",
      "title": "Article 15 Orders, Refunds, and Consumer Responsibilities",
      "subsections": [
        {
          "id": "15.1",
          "title": "15.1",
          "paragraphs": [
            "The Merchant shall fulfill orders in accordance with the commercial commitments it has made to consumers."
          ]
        },
        {
          "id": "15.2",
          "title": "15.2",
          "paragraphs": [
            "For refunds, returns, order cancellations, or consumer disputes caused by the Merchant, the Merchant shall bear corresponding responsibility in accordance with law."
          ]
        },
        {
          "id": "15.3",
          "title": "15.3",
          "paragraphs": [
            "FilixPay may, based on actual business processes, provide the Merchant with order, transaction, refund, or dispute-handling capabilities."
          ]
        },
        {
          "id": "15.4",
          "title": "15.4",
          "paragraphs": [
            "Except as otherwise provided by law, FilixPay does not substitute for the Merchant in bearing the operating responsibilities that the Merchant should bear as a provider of goods or services."
          ]
        }
      ]
    },
    {
      "id": "Article-16-Merchant-Data-and-Privacy",
      "title": "Article 16 Merchant Data and Privacy",
      "subsections": [
        {
          "id": "16.1",
          "title": "16.1",
          "paragraphs": [
            "Data generated in the course of the Merchant’s use of FilixPay services shall be processed in accordance with the FilixPay Privacy Policy and applicable data-protection rules."
          ]
        },
        {
          "id": "16.2",
          "title": "16.2",
          "paragraphs": [
            "If the Merchant processes personal information of its customers, consumers, or other third parties through FilixPay, it shall ensure that it has the authorization, legal basis, and necessary notices required for lawful processing of such data."
          ]
        },
        {
          "id": "16.3",
          "title": "16.3",
          "paragraphs": [
            "The Merchant shall not use FilixPay services to unlawfully collect, use, sell, disclose, or otherwise process personal information."
          ]
        },
        {
          "id": "16.4",
          "title": "16.4",
          "paragraphs": [
            "For data that the Merchant itself decides to collect and process, the Merchant shall bear corresponding data-protection responsibilities in accordance with law."
          ]
        }
      ]
    },
    {
      "id": "Article-17-Merchant-Content-and-Intellectual-Property",
      "title": "Article 17 Merchant Content and Intellectual Property",
      "subsections": [
        {
          "id": "17.1",
          "title": "17.1",
          "paragraphs": [
            "Intellectual property rights in goods information, images, text, brands, trademarks, and other content submitted or published by the Merchant on the FilixPay platform shall, in principle, remain with the Merchant or its lawful rights holders."
          ]
        },
        {
          "id": "17.2",
          "title": "17.2",
          "paragraphs": [
            "The Merchant grants FilixPay a non-exclusive right to use such content as necessary to provide, operate, display, maintain, and improve the relevant services."
          ]
        },
        {
          "id": "17.3",
          "title": "17.3",
          "paragraphs": [
            "The Merchant warrants that the content it submits does not infringe any third party’s intellectual property rights, privacy rights, or other lawful rights and interests."
          ]
        },
        {
          "id": "17.4",
          "title": "17.4",
          "paragraphs": [
            "Intellectual property rights in FilixPay’s platform software, technology, trademarks, interfaces, documentation, and other platform content belong to FilixPay or the relevant rights holders.",
            "Without authorization, the Merchant shall not copy, sell, lease, reverse engineer, or otherwise infringe such rights."
          ]
        }
      ]
    },
    {
      "id": "Article-18-Third-Party-Services",
      "title": "Article 18 Third-Party Services",
      "subsections": [
        {
          "id": "18.1",
          "title": "18.1",
          "paragraphs": [
            "Certain FilixPay services may depend on third-party payment institutions, banks, payment networks, infrastructure providers, cloud service providers, or other third-party services."
          ]
        },
        {
          "id": "18.2",
          "title": "18.2",
          "paragraphs": [
            "Third-party services may be subject to their own agreements, service rules, privacy policies, and fee rules."
          ]
        },
        {
          "id": "18.3",
          "title": "18.3",
          "paragraphs": [
            "For service changes caused by a third-party service provider’s systems, networks, policies, service scope, or other reasons, FilixPay will handle such matters within a reasonable scope, but does not guarantee the continued availability of third-party services."
          ]
        }
      ]
    },
    {
      "id": "Article-19-Service-Availability",
      "title": "Article 19 Service Availability",
      "subsections": [
        {
          "id": "19.1",
          "title": "19.1",
          "paragraphs": [
            "FilixPay will maintain the stability and security of the services within a reasonable scope."
          ]
        },
        {
          "id": "19.2",
          "title": "19.2",
          "paragraphs": [
            "FilixPay shall not bear liability beyond that required by law for service interruption or restriction caused by any of the following:"
          ],
          "bullets": [
            "scheduled maintenance;",
            "system upgrades;",
            "network failures;",
            "cloud service failures;",
            "third-party service failures;",
            "payment channel failures;",
            "hacking attacks;",
            "network security incidents;",
            "force majeure;",
            "requirements of government or regulatory authorities;",
            "changes in laws and regulations;",
            "other events beyond FilixPay’s reasonable control."
          ]
        }
      ]
    },
    {
      "id": "Article-20-Term-of-the-Agreement",
      "title": "Article 20 Term of the Agreement",
      "subsections": [
        {
          "id": "20.1",
          "title": "20.1",
          "paragraphs": [
            "This Agreement takes effect as of the date on which the Merchant completes acceptance of this Agreement and obtains eligibility for merchant services."
          ]
        },
        {
          "id": "20.2",
          "title": "20.2",
          "paragraphs": [
            "This Agreement remains in effect until terminated in accordance with this Agreement."
          ]
        }
      ]
    },
    {
      "id": "Article-21-Merchant-Initiated-Termination",
      "title": "Article 21 Merchant-Initiated Termination",
      "subsections": [
        {
          "id": "21.1",
          "title": "21.1",
          "paragraphs": [
            "The Merchant may apply to discontinue use of merchant services in accordance with the process provided by FilixPay."
          ]
        },
        {
          "id": "21.2",
          "title": "21.2",
          "paragraphs": [
            "Before terminating services, the Merchant shall properly handle:"
          ],
          "bullets": [
            "uncompleted orders;",
            "consumer refunds;",
            "Outstanding Service Fees;",
            "other unfulfilled obligations."
          ]
        },
        {
          "id": "21.3",
          "title": "21.3",
          "paragraphs": [
            "The Merchant’s cessation of use of the services does not relieve it of payment obligations and other responsibilities that arose before termination."
          ]
        }
      ]
    },
    {
      "id": "Article-22-Suspension-or-Termination-of-Services-by-FilixPay",
      "title": "Article 22 Suspension or Termination of Services by FilixPay",
      "subsections": [
        {
          "id": "22.1",
          "title": "22.1",
          "paragraphs": [
            "FilixPay may suspend or terminate all or part of the merchant services upon the occurrence of any of the following:"
          ],
          "bullets": [
            "the Merchant breaches this Agreement;",
            "the Merchant violates applicable laws and regulations;",
            "the Merchant presents material fraud or security risks;",
            "the Merchant presents material compliance risks;",
            "the Merchant fails to pay amounts due as agreed;",
            "the Merchant provides false or misleading materials;",
            "the Merchant engages in prohibited businesses;",
            "third-party payment or infrastructure services can no longer be provided;",
            "a regulatory authority or other competent authority so requires;",
            "other circumstances in which suspension or termination measures are required under this Agreement or applicable rules."
          ]
        },
        {
          "id": "22.2",
          "title": "22.2",
          "paragraphs": [
            "Where permitted by law and practicable, FilixPay will provide the Merchant with relevant notice.",
            "However, if immediate measures are necessary to prevent fraud, security risks, illegal conduct, or other material risks, FilixPay may take measures first and provide notice thereafter."
          ]
        },
        {
          "id": "22.3",
          "title": "22.3",
          "paragraphs": [
            "Termination of services does not affect payment, indemnification, confidentiality, intellectual property, data-processing, and other obligations that arose before termination and that should continue in effect."
          ]
        }
      ]
    },
    {
      "id": "Article-23-Liability-and-Disclaimers",
      "title": "Article 23 Liability and Disclaimers",
      "subsections": [
        {
          "id": "23.1",
          "title": "23.1",
          "paragraphs": [
            "FilixPay provides the relevant infrastructure services to the Merchant based on its then-existing service capabilities.",
            "Except as expressly required by law, FilixPay does not warrant that:"
          ],
          "bullets": [
            "the services will be uninterrupted at all times;",
            "all payment channels will always be available;",
            "all transactions can be successfully completed;",
            "any particular business will be profitable;",
            "relevant services will always be usable in a particular market or region."
          ]
        },
        {
          "id": "23.2",
          "title": "23.2",
          "paragraphs": [
            "The Merchant shall itself determine whether its business activities, goods, services, and business model are suitable under laws and regulations and for its own business needs."
          ]
        },
        {
          "id": "23.3",
          "title": "23.3",
          "paragraphs": [
            "Liability arising from the Merchant’s own business conduct, goods or services, consumer disputes, tax obligations, intellectual property disputes, and the like shall, in principle, be borne by the Merchant."
          ]
        },
        {
          "id": "23.4",
          "title": "23.4",
          "paragraphs": [
            "The scope of either party’s liability arising from this Agreement shall be subject to applicable law and the liability-limitation rules agreed in the parties’ valid agreements."
          ]
        }
      ]
    },
    {
      "id": "Article-24-Merchant-Indemnification",
      "title": "Article 24 Merchant Indemnification",
      "paragraphs": [
        "If FilixPay suffers third-party claims, penalties, losses, or reasonable expenses as a result of the Merchant’s breach of this Agreement, violation of laws and regulations, infringement of third-party rights, or business conduct, the Merchant shall bear corresponding responsibility to the extent permitted by applicable law.",
        "However, if the relevant losses are primarily caused by FilixPay’s own fault, each party’s responsibility shall be determined in accordance with applicable law and the parties’ respective proportions of fault."
      ]
    },
    {
      "id": "Article-25-Amendments-to-the-Agreement",
      "title": "Article 25 Amendments to the Agreement",
      "subsections": [
        {
          "id": "25.1",
          "title": "25.1",
          "paragraphs": [
            "FilixPay may update this Agreement based on business development, service changes, laws and regulations, or regulatory requirements."
          ]
        },
        {
          "id": "25.2",
          "title": "25.2",
          "paragraphs": [
            "For material changes, FilixPay will notify the Merchant by reasonable means."
          ]
        },
        {
          "id": "25.3",
          "title": "25.3",
          "paragraphs": [
            "Except as otherwise required by law, the updated Agreement applies to subsequent services as of the designated effective date."
          ]
        },
        {
          "id": "25.4",
          "title": "25.4",
          "paragraphs": [
            "If the Merchant does not agree to a material change, it may discontinue use of the relevant services and terminate merchant services in accordance with the applicable procedures.",
            "Continued use of the relevant services after a change takes effect constitutes acceptance of the updated Agreement."
          ]
        }
      ]
    },
    {
      "id": "Article-26-Changes-to-Merchant-Service-Fee-Rules",
      "title": "Article 26 Changes to Merchant Service Fee Rules",
      "subsections": [
        {
          "id": "26.1",
          "title": "26.1",
          "paragraphs": [
            "The current principal Service Fee standards are:",
            "Service Type: Service Fee",
            "FilixPay SaaS Collection: 0% (free)",
            "FilixPay e-commerce platform sales orders: 5%"
          ]
        },
        {
          "id": "26.2",
          "title": "26.2",
          "paragraphs": [
            "FilixPay may adjust service fee rates, fee items, billing rules, or payment rules based on business development."
          ]
        },
        {
          "id": "26.3",
          "title": "26.3",
          "paragraphs": [
            "Where changes involve material payment obligations of the Merchant, FilixPay shall notify the Merchant in accordance with this Agreement and determine the effective time to the extent permitted by applicable law."
          ]
        },
        {
          "id": "26.4",
          "title": "26.4",
          "paragraphs": [
            "Service Fees already accrued and payable by the Merchant before a change takes effect are not automatically waived by reason of subsequent changes to fee rules."
          ]
        }
      ]
    },
    {
      "id": "Article-27-Notices",
      "title": "Article 27 Notices",
      "subsections": [
        {
          "id": "27.1",
          "title": "27.1",
          "paragraphs": [
            "FilixPay may send notices to the Merchant by the following means:"
          ],
          "bullets": [
            "Merchant Center;",
            "registered email;",
            "in-account notifications;",
            "website announcements;",
            "other reasonable means."
          ]
        },
        {
          "id": "27.2",
          "title": "27.2",
          "paragraphs": [
            "The Merchant shall ensure that its contact information is true and valid, and shall update it promptly.",
            "If the Merchant is unable to receive notices because it failed to update its contact information in a timely manner, FilixPay shall not bear additional liability therefor."
          ]
        }
      ]
    },
    {
      "id": "Article-28-Confidentiality",
      "title": "Article 28 Confidentiality",
      "paragraphs": [
        "Each party shall take reasonable measures to keep confidential the other party’s non-public information obtained in the course of using the services under this Agreement.",
        "Disclosure required by laws and regulations, regulatory requirements, or competent authorities is excepted.",
        "This Article does not restrict FilixPay from lawfully processing relevant information for the purpose of providing services, conducting risk control, compliance review, accounting, or using necessary third-party services."
      ]
    },
    {
      "id": "Article-29-Relationship-of-Agreements",
      "title": "Article 29 Relationship of Agreements",
      "subsections": [
        {
          "id": "29.1",
          "title": "29.1",
          "paragraphs": [
            "This Agreement, together with the following documents, constitutes the rules framework for the Merchant’s use of FilixPay services:"
          ],
          "bullets": [
            "FilixPay Terms of Service;",
            "FilixPay Privacy Policy;",
            "FilixPay Merchant Service and Fee Rules;",
            "specific product or service rules;",
            "commercial agreements, orders, or other written documents separately entered into by the parties."
          ]
        },
        {
          "id": "29.2",
          "title": "29.2",
          "paragraphs": [
            "Where different provisions exist regarding the same matter, the order of precedence shall be determined as follows:",
            "However, matters involving data protection, privacy, security, or regulatory requirements shall also comply with applicable law and relevant specialized rules."
          ],
          "orderedBullets": [
            "special written agreements entered into by the parties for specific services;",
            "this Agreement;",
            "special fee and product rules applicable to merchant services;",
            "FilixPay general Terms of Service;",
            "other general platform rules."
          ]
        }
      ]
    },
    {
      "id": "Article-30-No-Agency-or-Partnership",
      "title": "Article 30 No Agency or Partnership",
      "paragraphs": [
        "Except as otherwise expressly agreed in writing by the parties, this Agreement does not constitute:",
        "Neither party may make commitments on behalf of the other without authorization."
      ],
      "bullets": [
        "a partnership;",
        "an agency;",
        "an employment relationship;",
        "a franchise;",
        "a joint operation;",
        "a commercial representation relationship."
      ]
    },
    {
      "id": "Article-31-Force-Majeure",
      "title": "Article 31 Force Majeure",
      "paragraphs": [
        "If an event beyond reasonable control causes a party to be unable to perform, or to delay performance of, its obligations under this Agreement, that party shall not, to the extent permitted by law, bear liability arising from such delay.",
        "Force majeure events include without limitation:",
        "The affected party shall take measures within a reasonable scope to mitigate the impact."
      ],
      "bullets": [
        "natural disasters;",
        "war;",
        "terrorist activities;",
        "large-scale cyberattacks;",
        "major infrastructure failures;",
        "government actions;",
        "major public events;",
        "changes in laws, regulations, or regulatory policies;",
        "other events that could not reasonably be foreseen, avoided, or overcome."
      ]
    },
    {
      "id": "Article-32-Severability",
      "title": "Article 32 Severability",
      "paragraphs": [
        "If any provision of this Agreement is held to be invalid, illegal, or unenforceable, that provision shall be adjusted or deemed inapplicable to the extent necessary, without affecting the validity of the remaining provisions."
      ]
    },
    {
      "id": "Article-33-Assignment-of-Rights-and-Obligations",
      "title": "Article 33 Assignment of Rights and Obligations",
      "paragraphs": [
        "Neither party may assign the principal rights and obligations under this Agreement as a whole to a third party without the other party’s prior written consent, except where permitted by law or where the assignment occurs due to reasonable commercial arrangements such as corporate reorganization, merger, or acquisition."
      ]
    },
    {
      "id": "Article-34-Entire-Agreement",
      "title": "Article 34 Entire Agreement",
      "paragraphs": [
        "This Agreement and the related rules expressly incorporated herein constitute the entire agreement between the parties with respect to merchant service matters.",
        "If the parties separately enter into a written agreement making different arrangements on specific matters, such special agreement shall prevail."
      ]
    },
    {
      "id": "Article-35-Governing-Law-and-Dispute-Resolution",
      "title": "Article 35 Governing Law and Dispute Resolution",
      "paragraphs": [
        "The governing law, jurisdiction, and dispute-resolution method for this Agreement shall be determined by reference to FilixPay’s actual contracting entity and its place of commercial operations.",
        "Before formally publishing this Agreement, FilixPay shall supplement and confirm:",
        "Until the foregoing information is formally determined, this Article shall not be construed as a final choice of any particular jurisdiction."
      ],
      "bullets": [
        "the full legal name of the contracting entity;",
        "the place of registration or principal place of business;",
        "the governing law;",
        "the competent court or arbitral institution;",
        "the place of dispute resolution;",
        "the formal legal notice address."
      ]
    },
    {
      "id": "Article-36-Contact-Us",
      "title": "Article 36 Contact Us",
      "paragraphs": [
        "If the Merchant has questions regarding this Agreement, merchant services, Service Fee invoices/bills, or other related matters, it may contact FilixPay through the official contact methods published on the FilixPay website and in the Merchant Center.",
        "The formally published version shall supplement FilixPay’s actually used:"
      ],
      "bullets": [
        "business contact methods;",
        "legal notice email;",
        "merchant service support channels;",
        "other necessary statutory contact information."
      ]
    },
    {
      "id": "Article-37-Effectiveness",
      "title": "Article 37 Effectiveness",
      "paragraphs": [
        "This Agreement takes effect as of the date on which the Merchant completes acceptance in the manner designated by FilixPay.",
        "By completing onboarding, activating, or continuing to use the relevant merchant services, the Merchant confirms that it has read, understood, and accepted this Agreement and the related rules applicable to its services."
      ]
    },
    {
      "id": "Appendix-I-Merchant-Service-Fee-Summary",
      "title": "Appendix I: Merchant Service Fee Summary",
      "paragraphs": [
        "Item: V1 Rules",
        "FilixPay SaaS Collection: Free (0%)",
        "E-commerce platform sales orders: 5%",
        "Accrual of Service Fees: Accrues when orders or transactions meeting billing conditions occur",
        "Billing period: Calendar month",
        "Invoice/bill generation time: Preceding month’s invoice/bill generated on the 1st of each month",
        "Payment Threshold: Outstanding Balance accumulates to ¥500",
        "Payment deadline: After the threshold is reached, pay by the 5th of the month in which the invoice/bill is generated",
        "Below ¥500: Payment obligation not yet triggered; balance continues to accumulate",
        "Nature of ¥500: Payment-trigger threshold, not a free allowance",
        "Outstanding Balance: Does not automatically clear at the end of a calendar month"
      ]
    },
    {
      "id": "Appendix-II-Core-Commercial-Rules",
      "title": "Appendix II: Core Commercial Rules",
      "subsections": [
        {
          "id": "1.-SaaS-Collection",
          "title": "1. SaaS Collection",
          "paragraphs": [
            "FilixPay SaaS Collection is currently free of charge."
          ]
        },
        {
          "id": "2.-E-commerce-Platform-Sales",
          "title": "2. E-commerce Platform Sales",
          "paragraphs": [
            "Sales orders generated through the FilixPay e-commerce platform currently incur a platform service fee of 5% of the order amount."
          ]
        },
        {
          "id": "3.-Payment-of-Service-Fees",
          "title": "3. Payment of Service Fees",
          "paragraphs": [
            "Service Fees are calculated based on business events that actually occur and meet billing conditions. The preceding month’s invoice/bill is generated on the 1st of each month. When the Outstanding Balance is below RMB 500, the payment obligation is not yet triggered; when the Outstanding Balance reaches or exceeds RMB 500, the payment obligation is triggered, and the Merchant shall complete payment by the 5th of that month."
          ]
        },
        {
          "id": "4.-Nature-of-the-Threshold",
          "title": "4. Nature of the Threshold",
          "paragraphs": [
            "RMB 500 is a payment-trigger threshold, not a free allowance, fee-free quota, or monthly fee-waiver allowance.",
            "Last Updated: September 7, 2026"
          ]
        }
      ]
    }
  ]
} as LegalDocument;

export const MERCHANT_TERMS_BY_LOCALE: Record<LegalContentLocale, LegalDocument> = {
  zh: MERCHANT_TERMS_ZH,
  en: MERCHANT_TERMS_EN,
};
