import type { LegalContentLocale } from "@/lib/legal/content-locales";
import type { LegalDocument } from "./types";

/**
 * SSOT ZH: filix-pay/docs/FilixPay 商户服务与收费规则 V1.md; EN: FilixPay Merchant Service and Fee Rules V1.en.md
 * Generated by scripts/generate-merchant-legal-from-md.mjs — do not hand-edit commercial rules.
 */
const MERCHANT_FEES_ZH: LegalDocument = {
  "slug": "merchant-fees",
  "status": "draft",
  "title": "FilixPay 商户服务与收费规则",
  "lastUpdated": "2026-09-07",
  "notice": null,
  "sections": [
    {
      "id": "meta",
      "title": "",
      "paragraphs": [
        "Version: V1.0.0",
        "Status: Frozen",
        "Last Updated: 2026-09-07"
      ]
    },
    {
      "id": "1.-文档目的",
      "title": "1. 文档目的",
      "paragraphs": [
        "本规则用于明确 FilixPay 商户入驻后的服务范围、平台服务费及服务费结算规则。",
        "本规则适用于通过 FilixPay 开通商户服务的商户，并作为《FilixPay 商户服务协议》的组成部分或配套收费规则使用。",
        "本规则仅约定平台服务费相关商业规则，不改变 FilixPay 支付、资金流转、结算、账务及其他服务的独立业务规则。"
      ]
    },
    {
      "id": "2.-商户服务模式",
      "title": "2. 商户服务模式",
      "paragraphs": [
        "FilixPay 当前提供两类主要商户使用场景："
      ],
      "subsections": [
        {
          "id": "2.1-FilixPay-SaaS-收款",
          "title": "2.1 FilixPay SaaS 收款",
          "paragraphs": [
            "商户使用 FilixPay 提供的支付基础设施、支付能力及相关 SaaS 服务完成自身业务收款。",
            "当前平台服务费：免费。",
            "即：",
            "FilixPay SaaS 收款当前不收取平台服务费。",
            "FilixPay 可根据未来业务规模、服务内容或商业政策调整相关收费标准。任何收费调整应按照《FilixPay 商户服务协议》及适用法律规定提前通知商户。"
          ]
        },
        {
          "id": "2.2-FilixPay-电商平台销售订单",
          "title": "2.2 FilixPay 电商平台销售订单",
          "paragraphs": [
            "商户通过 FilixPay 电商平台产生销售订单并完成交易的，FilixPay 按符合计费条件的订单收取平台服务费。",
            "当前平台服务费率：订单金额的 5%。",
            "该服务费适用于符合 FilixPay 平台计费条件的电商销售订单。"
          ]
        }
      ]
    },
    {
      "id": "3.-服务费计算",
      "title": "3. 服务费计算",
      "subsections": [
        {
          "id": "3.1-SaaS-收款",
          "title": "3.1 SaaS 收款",
          "paragraphs": [
            "FilixPay SaaS 收款当前服务费率为：",
            "0%",
            "因此，符合 SaaS 收款定义的交易当前不产生 FilixPay 平台服务费。"
          ]
        },
        {
          "id": "3.2-电商平台销售订单",
          "title": "3.2 电商平台销售订单",
          "paragraphs": [
            "符合计费条件的电商平台销售订单，按照以下规则计算服务费：",
            "服务费 = 计费订单金额 × 5%",
            "具体计费金额及计费时点以 FilixPay 实际记录的业务订单及相关计费规则为准。",
            "对于退款、取消、撤销、异常交易或其他特殊交易，其是否调整已产生的服务费，以 FilixPay 相应的计费规则及商户服务协议为准。"
          ]
        }
      ]
    },
    {
      "id": "4.-服务费产生与账单",
      "title": "4. 服务费产生与账单",
      "subsections": [
        {
          "id": "4.1-按业务事件计费",
          "title": "4.1 按业务事件计费",
          "paragraphs": [
            "FilixPay 服务费按照实际发生的符合计费条件的业务订单或交易产生。",
            "没有符合计费条件的订单或交易，不产生相应的平台服务费。",
            "因此，商户不会因为仅开通 FilixPay 商户服务而产生固定的平台服务费。"
          ]
        },
        {
          "id": "4.2-月度账单",
          "title": "4.2 月度账单",
          "paragraphs": [
            "FilixPay 按月汇总商户上一自然月产生的服务费。",
            "每月 1 日生成上一自然月的服务费账单。",
            "例如：",
            "账单应展示至少包括："
          ],
          "bullets": [
            "9 月产生的服务费，于 10 月 1 日生成账单；",
            "10 月产生的服务费，于 11 月 1 日生成账单。",
            "账单周期；",
            "计费订单或交易数量；",
            "计费金额；",
            "服务费金额；",
            "已支付金额；",
            "未结清余额；",
            "当前是否达到付款阈值。"
          ]
        }
      ]
    },
    {
      "id": "5.-未结清余额与付款阈值",
      "title": "5. 未结清余额与付款阈值",
      "subsections": [
        {
          "id": "5.1-付款阈值",
          "title": "5.1 付款阈值",
          "paragraphs": [
            "FilixPay 对商户服务费采用未结清余额累计达到付款阈值后付款的方式。",
            "当前付款阈值为：",
            "人民币 500 元。",
            "这里的人民币 500 元是付款触发阈值，不是免收费额度。"
          ]
        },
        {
          "id": "5.2-未达到付款阈值",
          "title": "5.2 未达到付款阈值",
          "paragraphs": [
            "当商户的服务费未结清余额累计低于人民币 500 元时：",
            "例如：",
            "9 月服务费：人民币 300 元 未结清余额：人民币 300 元 因未达到人民币 500 元付款阈值，暂不触发付款义务。"
          ],
          "bullets": [
            "服务费仍然正常产生；",
            "服务费仍然计入商户未结清余额；",
            "商户暂不需要支付；",
            "未结清余额继续累计至后续账期。"
          ]
        },
        {
          "id": "5.3-达到付款阈值",
          "title": "5.3 达到付款阈值",
          "paragraphs": [
            "当商户未结清服务费余额累计达到或超过人民币 500 元时，即触发付款义务。",
            "例如：",
            "上期未结清余额：人民币 300 元 本期新增服务费：人民币 250 元 未结清余额：人民币 550 元 已达到人民币 500 元付款阈值，商户应支付人民币 550 元未结清服务费。",
            "付款阈值针对的是未结清余额，而不是单个账单金额，也不是每个自然月重新计算的免付额度。"
          ]
        }
      ]
    },
    {
      "id": "6.-付款时间",
      "title": "6. 付款时间",
      "paragraphs": [
        "当商户未结清服务费余额达到或超过人民币 500 元后，商户应在相应账单要求的付款期限内完成支付。",
        "当前付款期限为：",
        "账单生成当月 5 日前。",
        "例如：",
        "10 月 1 日生成 9 月服务费账单，且未结清余额达到人民币 500 元，则商户应于 10 月 5 日前完成支付。",
        "商户未按期支付已达到付款阈值的服务费，FilixPay 可依据《FilixPay 商户服务协议》采取相应的服务限制、暂停或其他合同约定措施。"
      ]
    },
    {
      "id": "7.-支付后的余额",
      "title": "7. 支付后的余额",
      "paragraphs": [
        "商户完成服务费支付后，相应已支付金额从未结清余额中扣除。",
        "例如：",
        "未结清余额：人民币 550 元 本次支付：人民币 550 元 支付后未结清余额：人民币 0 元。",
        "如商户仅支付部分金额，则剩余未支付金额继续计入未结清余额，并按照相关规则处理。"
      ]
    },
    {
      "id": "8.-服务费规则示例",
      "title": "8. 服务费规则示例",
      "subsections": [
        {
          "id": "示例一SaaS-收款",
          "title": "示例一：SaaS 收款",
          "paragraphs": [
            "商户通过 FilixPay SaaS 完成收款：",
            "收款金额：人民币 10,000 元 服务费率：0% FilixPay 服务费：人民币 0 元"
          ]
        },
        {
          "id": "示例二电商平台销售",
          "title": "示例二：电商平台销售",
          "paragraphs": [
            "商户通过 FilixPay 电商平台产生销售订单：",
            "订单金额：人民币 10,000 元 服务费率：5% FilixPay 服务费：人民币 500 元",
            "如果该商户此前没有未结清服务费，则该笔费用使未结清余额达到人民币 500 元，触发付款义务。"
          ]
        },
        {
          "id": "示例三未达到付款阈值",
          "title": "示例三：未达到付款阈值",
          "paragraphs": [
            "上月未结清余额：人民币 200 元 本月新增服务费：人民币 180 元 当前未结清余额：人民币 380 元",
            "由于未达到人民币 500 元付款阈值，商户暂不需要付款。",
            "人民币 380 元继续作为未结清余额累计。"
          ]
        },
        {
          "id": "示例四跨月达到付款阈值",
          "title": "示例四：跨月达到付款阈值",
          "paragraphs": [
            "上月未结清余额：人民币 380 元 本月新增服务费：人民币 200 元 当前未结清余额：人民币 580 元",
            "由于未结清余额已经达到人民币 500 元，商户应按照当期账单要求，于当月 5 日前支付人民币 580 元。"
          ]
        }
      ]
    },
    {
      "id": "9.-费用调整",
      "title": "9. 费用调整",
      "paragraphs": [
        "FilixPay 当前商业规则为：",
        "服务类型：当前服务费",
        "FilixPay SaaS 收款：免费（0%）",
        "FilixPay 电商平台销售订单：5%",
        "未来 FilixPay 可根据业务发展、服务范围、市场情况及商业政策对服务费规则进行调整。",
        "例如未来可能增加：",
        "未来新增或调整收费项目时，应按照《FilixPay 商户服务协议》约定的通知及生效机制执行。"
      ],
      "bullets": [
        "SaaS 收款服务费；",
        "不同支付渠道的差异化费率；",
        "商户等级或交易规模对应的费率；",
        "企业客户定制费率；",
        "其他增值服务费用。"
      ]
    },
    {
      "id": "10.-与商户服务协议的关系",
      "title": "10. 与商户服务协议的关系",
      "paragraphs": [
        "本规则与《FilixPay 商户服务协议》配套使用。",
        "如本规则与双方另行签署的商业协议、订单、企业服务协议或其他书面约定存在差异，以双方针对具体商户签署并生效的专门约定为准。",
        "除服务费及账单规则外，商户使用 FilixPay 服务仍应遵守："
      ],
      "bullets": [
        "FilixPay 服务条款；",
        "FilixPay 隐私政策；",
        "商户服务协议；",
        "适用的产品及技术规则；",
        "适用法律法规；",
        "FilixPay 适用的合规、风险及安全要求。"
      ]
    },
    {
      "id": "11.-商户入驻页面展示摘要",
      "title": "11. 商户入驻页面展示摘要",
      "paragraphs": [
        "在商户完成入驻前，FilixPay 应向商户清晰展示当前核心商业规则：",
        "### 商户服务费 FilixPay SaaS 收款：免费 使用 FilixPay SaaS 完成自身业务收款，当前不收取平台服务费。 电商平台销售订单：5% 通过 FilixPay 电商平台产生的销售订单，按订单金额的 5% 收取平台服务费。 付款规则 - 服务费仅在产生符合计费条件的订单或交易时产生； - 每月 1 日生成上月服务费账单； - 未结清服务费余额低于人民币 500 元时，暂不触发付款义务； - 未结清余额达到或超过人民币 500 元时，触发付款义务； - 达到付款阈值后，应于当月 5 日前完成支付； - 人民币 500 元为付款触发阈值，并非免收费额度。 详细规则请参阅《FilixPay 商户服务协议》及《FilixPay 商户服务与收费规则》。",
        "商户完成入驻前，应确认已阅读并同意适用的商户服务协议。"
      ]
    },
    {
      "id": "12.-V1-冻结原则",
      "title": "12. V1 冻结原则",
      "paragraphs": [
        "V1 阶段采用以下商业规则："
      ],
      "orderedBullets": [
        "FilixPay SaaS 收款免费。",
        "FilixPay 电商平台销售订单服务费为 5%。",
        "服务费仅在发生符合计费条件的业务事件时产生。",
        "每月 1 日生成上一自然月服务费账单。",
        "服务费采用未结清余额累计机制。",
        "未结清余额达到人民币 500 元时触发付款义务。",
        "人民币 500 元不是免收费额度。",
        "达到付款阈值后，商户应于当月 5 日前完成支付。",
        "未达到付款阈值的未结清服务费继续累计，不因自然月结束而清零。",
        "商业费率与账务实现应保持解耦，不以单一 Merchant `fee_rate` 作为平台级收费模型。",
        "后续增加新的收费类型、费率或商业方案时，不应破坏现有计费及账单模型。"
      ]
    },
    {
      "id": "13.-计费模型建议",
      "title": "13. 计费模型建议",
      "paragraphs": [
        "平台内部不应将本规则简单实现为商户级固定费率。",
        "推荐抽象为：",
        "Billable Event\n      ↓\nFee Rule\n      ↓\nService Fee\n      ↓\nMonthly Invoice\n      ↓\nUnsettled Fee Balance\n      ↓\nPayment Threshold\n      ↓\nPayment",
        "V1 示例：",
        "SAAS_PAYMENT\n    fee_rate = 0%\n\nCOMMERCE_ORDER\n    fee_rate = 5%",
        "其中：",
        "该模型允许未来增加新的业务类型、费率及商业方案，而无需改变商户核心模型或资金账务模型。"
      ],
      "bullets": [
        "`Billable Event` 表示实际发生的可计费业务事件；",
        "`Fee Rule` 定义该业务事件适用的收费规则；",
        "`Service Fee` 表示由业务事件产生的服务费；",
        "`Monthly Invoice` 汇总账期内服务费；",
        "`Unsettled Fee Balance` 表示商户当前尚未结清的服务费；",
        "`Payment Threshold` 判断是否触发付款义务；",
        "`Payment` 表示商户实际完成的服务费支付。"
      ]
    }
  ]
} as LegalDocument;

const MERCHANT_FEES_EN: LegalDocument = {
  "slug": "merchant-fees",
  "status": "draft",
  "title": "FilixPay Merchant Service & Fee Rules",
  "lastUpdated": "2026-09-07",
  "notice": null,
  "sections": [
    {
      "id": "meta",
      "title": "",
      "paragraphs": [
        "Version: V1.0.0",
        "Status: Frozen",
        "Last Updated: 2026-09-07"
      ]
    },
    {
      "id": "1.-Purpose-of-This-Document",
      "title": "1. Purpose of This Document",
      "paragraphs": [
        "These Rules set out the scope of services available to merchants after onboarding to FilixPay, the platform service fees, and the rules for settlement of such service fees.",
        "These Rules apply to merchants that activate merchant services through FilixPay, and shall be used as an integral part of, or as accompanying fee rules to, the *FilixPay Merchant Service Agreement*.",
        "These Rules address only the commercial rules relating to platform service fees and do not alter the independent business rules applicable to FilixPay payments, fund flows, settlement, accounting, or other services."
      ]
    },
    {
      "id": "2.-Merchant-Service-Models",
      "title": "2. Merchant Service Models",
      "paragraphs": [
        "FilixPay currently provides two primary merchant use cases:"
      ],
      "subsections": [
        {
          "id": "2.1-FilixPay-SaaS-Payment-Collection",
          "title": "2.1 FilixPay SaaS Payment Collection",
          "paragraphs": [
            "Merchants use the payment infrastructure, payment capabilities, and related SaaS services provided by FilixPay to collect payments for their own business.",
            "Current platform service fee: Free.",
            "That is:",
            "FilixPay SaaS Payment Collection currently does not charge a platform service fee.",
            "FilixPay may adjust the applicable fee standards in the future based on business scale, service scope, or commercial policy. Any fee adjustment shall be notified to merchants in advance in accordance with the *FilixPay Merchant Service Agreement* and applicable law."
          ]
        },
        {
          "id": "2.2-FilixPay-Commerce-Platform-Sales-Orders",
          "title": "2.2 FilixPay Commerce Platform Sales Orders",
          "paragraphs": [
            "Where a merchant generates sales orders and completes transactions through the FilixPay commerce platform, FilixPay charges a platform service fee on orders that meet the fee-charging conditions.",
            "Current platform service fee rate: 5% of the order amount.",
            "This service fee applies to commerce sales orders that meet FilixPay’s platform fee-charging conditions."
          ]
        }
      ]
    },
    {
      "id": "3.-Calculation-of-Service-Fees",
      "title": "3. Calculation of Service Fees",
      "subsections": [
        {
          "id": "3.1-SaaS-Payment-Collection",
          "title": "3.1 SaaS Payment Collection",
          "paragraphs": [
            "The current service fee rate for FilixPay SaaS Payment Collection is:",
            "0%",
            "Accordingly, transactions that fall within the definition of SaaS Payment Collection currently do not give rise to FilixPay platform service fees."
          ]
        },
        {
          "id": "3.2-Commerce-Platform-Sales-Orders",
          "title": "3.2 Commerce Platform Sales Orders",
          "paragraphs": [
            "For commerce platform sales orders that meet the fee-charging conditions, service fees are calculated as follows:",
            "Service Fee = Billable Order Amount × 5%",
            "The specific billable amount and the timing of fee charging shall be determined by the business orders actually recorded by FilixPay and the applicable fee-charging rules.",
            "Whether refunds, cancellations, reversals, abnormal transactions, or other special transactions result in an adjustment to service fees already incurred shall be determined by FilixPay’s applicable fee-charging rules and the merchant service agreement."
          ]
        }
      ]
    },
    {
      "id": "4.-Accrual-of-Service-Fees-and-Invoices",
      "title": "4. Accrual of Service Fees and Invoices",
      "subsections": [
        {
          "id": "4.1-Fee-Charging-Based-on-Business-Events",
          "title": "4.1 Fee Charging Based on Business Events",
          "paragraphs": [
            "FilixPay service fees are incurred based on business orders or transactions that actually occur and meet the fee-charging conditions.",
            "Where there are no orders or transactions that meet the fee-charging conditions, no corresponding platform service fee is incurred.",
            "Accordingly, a merchant does not incur a fixed platform service fee merely by activating FilixPay merchant services."
          ]
        },
        {
          "id": "4.2-Monthly-Invoices",
          "title": "4.2 Monthly Invoices",
          "paragraphs": [
            "FilixPay aggregates on a monthly basis the service fees incurred by a merchant in the preceding calendar month.",
            "On the 1st day of each month, an invoice is generated for the service fees of the preceding calendar month.",
            "For example:",
            "An invoice shall display at least the following:"
          ],
          "bullets": [
            "Service fees incurred in September are invoiced on October 1;",
            "Service fees incurred in October are invoiced on November 1.",
            "Billing period;",
            "Number of billable orders or transactions;",
            "Billable amount;",
            "Service fee amount;",
            "Amount already paid;",
            "Unsettled balance;",
            "Whether the payment threshold is currently met."
          ]
        }
      ]
    },
    {
      "id": "5.-Unsettled-Balance-and-Payment-Threshold",
      "title": "5. Unsettled Balance and Payment Threshold",
      "subsections": [
        {
          "id": "5.1-Payment-Threshold",
          "title": "5.1 Payment Threshold",
          "paragraphs": [
            "FilixPay adopts a model under which merchant service fees become payable when the cumulative unsettled balance reaches the payment threshold.",
            "The current payment threshold is:",
            "RMB 500.",
            "The RMB 500 amount is a payment-trigger threshold, not a free allowance."
          ]
        },
        {
          "id": "5.2-Below-the-Payment-Threshold",
          "title": "5.2 Below the Payment Threshold",
          "paragraphs": [
            "When a merchant’s cumulative unsettled service fee balance is below RMB 500:",
            "For example:",
            "September service fees: RMB 300 Unsettled balance: RMB 300 Because the RMB 500 payment threshold has not been reached, no payment obligation is triggered for the time being."
          ],
          "bullets": [
            "Service fees continue to accrue normally;",
            "Service fees continue to be credited to the merchant’s unsettled balance;",
            "The merchant is not yet required to make payment;",
            "The unsettled balance continues to accumulate into subsequent billing periods."
          ]
        },
        {
          "id": "5.3-Reaching-the-Payment-Threshold",
          "title": "5.3 Reaching the Payment Threshold",
          "paragraphs": [
            "When a merchant’s cumulative unsettled service fee balance reaches or exceeds RMB 500, a payment obligation is triggered.",
            "For example:",
            "Prior unsettled balance: RMB 300 Newly accrued service fees in the current period: RMB 250 Unsettled balance: RMB 550 The RMB 500 payment threshold has been reached; the merchant shall pay the unsettled service fees of RMB 550.",
            "The payment threshold applies to the unsettled balance, not to the amount of any single invoice, and is not a free-payment allowance recalculated for each calendar month."
          ]
        }
      ]
    },
    {
      "id": "6.-Payment-Timing",
      "title": "6. Payment Timing",
      "paragraphs": [
        "When a merchant’s unsettled service fee balance reaches or exceeds RMB 500, the merchant shall complete payment within the payment period required by the corresponding invoice.",
        "The current payment deadline is:",
        "By the 5th day of the month in which the invoice is generated.",
        "For example:",
        "If an invoice for September service fees is generated on October 1 and the unsettled balance has reached RMB 500, the merchant shall complete payment by October 5.",
        "If a merchant fails to pay on time service fees that have reached the payment threshold, FilixPay may take corresponding measures such as service restrictions, suspension, or other contractually agreed actions pursuant to the *FilixPay Merchant Service Agreement*."
      ]
    },
    {
      "id": "7.-Balance-After-Payment",
      "title": "7. Balance After Payment",
      "paragraphs": [
        "After a merchant completes payment of service fees, the corresponding paid amount is deducted from the unsettled balance.",
        "For example:",
        "Unsettled balance: RMB 550 Payment made: RMB 550 Unsettled balance after payment: RMB 0.",
        "If a merchant pays only part of the amount, the remaining unpaid amount continues to be included in the unsettled balance and is handled in accordance with the applicable rules."
      ]
    },
    {
      "id": "8.-Service-Fee-Rule-Examples",
      "title": "8. Service Fee Rule Examples",
      "subsections": [
        {
          "id": "Example-1-SaaS-Payment-Collection",
          "title": "Example 1: SaaS Payment Collection",
          "paragraphs": [
            "A merchant collects payments through FilixPay SaaS:",
            "Collection amount: RMB 10,000 Service fee rate: 0% FilixPay service fee: RMB 0"
          ]
        },
        {
          "id": "Example-2-Commerce-Platform-Sales",
          "title": "Example 2: Commerce Platform Sales",
          "paragraphs": [
            "A merchant generates a sales order through the FilixPay commerce platform:",
            "Order amount: RMB 10,000 Service fee rate: 5% FilixPay service fee: RMB 500",
            "If the merchant previously had no unsettled service fees, this fee causes the unsettled balance to reach RMB 500 and triggers a payment obligation."
          ]
        },
        {
          "id": "Example-3-Below-the-Payment-Threshold",
          "title": "Example 3: Below the Payment Threshold",
          "paragraphs": [
            "Prior month unsettled balance: RMB 200 Newly accrued service fees this month: RMB 180 Current unsettled balance: RMB 380",
            "Because the RMB 500 payment threshold has not been reached, the merchant is not yet required to make payment.",
            "The RMB 380 continues to accumulate as the unsettled balance."
          ]
        },
        {
          "id": "Example-4-Crossing-Months-to-Reach-the-Payment-Threshold",
          "title": "Example 4: Crossing Months to Reach the Payment Threshold",
          "paragraphs": [
            "Prior month unsettled balance: RMB 380 Newly accrued service fees this month: RMB 200 Current unsettled balance: RMB 580",
            "Because the unsettled balance has reached RMB 500, the merchant shall, in accordance with the current invoice requirements, pay RMB 580 by the 5th day of the current month."
          ]
        }
      ]
    },
    {
      "id": "9.-Fee-Adjustments",
      "title": "9. Fee Adjustments",
      "paragraphs": [
        "FilixPay’s current commercial rules are:",
        "Service Type：Current Service Fee",
        "FilixPay SaaS Payment Collection：Free (0%)",
        "FilixPay Commerce Platform Sales Orders：5%",
        "In the future, FilixPay may adjust the service fee rules based on business development, service scope, market conditions, and commercial policy.",
        "For example, future additions may include:",
        "When new fee items are added or existing fees are adjusted in the future, such changes shall be implemented in accordance with the notice and effectiveness mechanisms set out in the *FilixPay Merchant Service Agreement*."
      ],
      "bullets": [
        "Service fees for SaaS Payment Collection;",
        "Differentiated rates by payment channel;",
        "Rates corresponding to merchant tier or transaction volume;",
        "Customized rates for enterprise customers;",
        "Fees for other value-added services."
      ]
    },
    {
      "id": "10.-Relationship-to-the-Merchant-Service-Agreement",
      "title": "10. Relationship to the Merchant Service Agreement",
      "paragraphs": [
        "These Rules are used in conjunction with the *FilixPay Merchant Service Agreement*.",
        "If these Rules conflict with a commercial agreement, order, enterprise service agreement, or other written arrangement separately executed by the parties, the specific terms signed and in effect for the particular merchant shall prevail.",
        "In addition to the service fee and invoice rules, merchants using FilixPay services shall continue to comply with:"
      ],
      "bullets": [
        "FilixPay Terms of Service;",
        "FilixPay Privacy Policy;",
        "the Merchant Service Agreement;",
        "applicable product and technical rules;",
        "applicable laws and regulations;",
        "FilixPay’s applicable compliance, risk, and security requirements."
      ]
    },
    {
      "id": "11.-Summary-Displayed-on-the-Merchant-Onboarding-Page",
      "title": "11. Summary Displayed on the Merchant Onboarding Page",
      "paragraphs": [
        "Before a merchant completes onboarding, FilixPay shall clearly present the current core commercial rules to the merchant:",
        "### Merchant Service Fees FilixPay SaaS Payment Collection: Free Using FilixPay SaaS to collect payments for the merchant’s own business currently does not incur a platform service fee. Commerce Platform Sales Orders: 5% Sales orders generated through the FilixPay commerce platform are charged a platform service fee equal to 5% of the order amount. Payment Rules - Service fees are incurred only when orders or transactions that meet the fee-charging conditions occur; - An invoice for the prior month’s service fees is generated on the 1st day of each month; - When the unsettled service fee balance is below RMB 500, no payment obligation is triggered for the time being; - When the unsettled balance reaches or exceeds RMB 500, a payment obligation is triggered; - After the payment threshold is reached, payment shall be completed by the 5th day of the current month; - RMB 500 is a payment-trigger threshold, not a free allowance. For detailed rules, please refer to the *FilixPay Merchant Service Agreement* and the *FilixPay Merchant Service & Fee Rules*.",
        "Before completing onboarding, the merchant shall confirm that it has read and agreed to the applicable merchant service agreement."
      ]
    },
    {
      "id": "12.-V1-Freeze-Principles",
      "title": "12. V1 Freeze Principles",
      "paragraphs": [
        "The V1 stage adopts the following commercial rules:"
      ],
      "orderedBullets": [
        "FilixPay SaaS Payment Collection is free.",
        "The service fee for FilixPay Commerce Platform Sales Orders is 5%.",
        "Service fees are incurred only when billable business events that meet the fee-charging conditions occur.",
        "An invoice for the preceding calendar month’s service fees is generated on the 1st day of each month.",
        "Service fees use a cumulative unsettled balance mechanism.",
        "A payment obligation is triggered when the unsettled balance reaches RMB 500.",
        "RMB 500 is not a free allowance.",
        "After the payment threshold is reached, the merchant shall complete payment by the 5th day of the current month.",
        "Unsettled service fees that have not reached the payment threshold continue to accumulate and do not reset to zero at the end of a calendar month.",
        "Commercial fee rates and accounting implementation shall remain decoupled; a single Merchant `fee_rate` shall not be used as the platform-level fee model.",
        "Subsequent additions of new fee types, rates, or commercial plans shall not break the existing fee-charging and invoicing model."
      ]
    },
    {
      "id": "13.-Recommended-Fee-Model",
      "title": "13. Recommended Fee Model",
      "paragraphs": [
        "Internally, the platform should not implement these Rules simply as a fixed merchant-level fee rate.",
        "The recommended abstraction is:",
        "Billable Event\n      ↓\nFee Rule\n      ↓\nService Fee\n      ↓\nMonthly Invoice\n      ↓\nUnsettled Fee Balance\n      ↓\nPayment Threshold\n      ↓\nPayment",
        "V1 example:",
        "SAAS_PAYMENT\n    fee_rate = 0%\n\nCOMMERCE_ORDER\n    fee_rate = 5%",
        "Where:",
        "This model allows new business types, fee rates, and commercial plans to be added in the future without changing the merchant core model or the fund accounting model."
      ],
      "bullets": [
        "`Billable Event` means a billable business event that actually occurs;",
        "`Fee Rule` defines the fee rule applicable to that business event;",
        "`Service Fee` means the service fee arising from the business event;",
        "`Monthly Invoice` aggregates service fees for the billing period;",
        "`Unsettled Fee Balance` means the merchant’s currently unsettled service fees;",
        "`Payment Threshold` determines whether a payment obligation is triggered;",
        "`Payment` means the service fee payment actually completed by the merchant."
      ]
    }
  ]
} as LegalDocument;

export const MERCHANT_FEES_BY_LOCALE: Record<LegalContentLocale, LegalDocument> = {
  zh: MERCHANT_FEES_ZH,
  en: MERCHANT_FEES_EN,
};
